import { FiCheckSquare } from 'react-icons/fi';
import { AttendanceRegister } from '../../components/attendance/AttendanceRegister';
import { AttendanceSessionList } from '../../components/attendance/AttendanceSessionList';
import { useAttendanceRegister } from '../../components/attendance/useAttendanceRegister';
import { EmptyBlock,ErrorBlock,LoadingBlock } from '../../components/common/PageState';
export function TeacherAttendance(){
  const r=useAttendanceRegister();
  return <div className="space-y-5"><section className="card flex-row items-center justify-between gap-4 border border-base-300 bg-base-100 p-6"><div><span className="mb-3 grid size-10 place-items-center rounded-xl bg-neutral text-neutral-content"><FiCheckSquare aria-hidden size={20}/></span><h1 className="text-3xl font-semibold">Attendance</h1><p className="mt-2 text-xs text-muted">Choose a session. Mark. Save.</p></div><img src="/illustrations/study-books.webp" alt="" width={144} height={120} className="h-24 w-28 shrink-0 object-contain sm:h-28 sm:w-36"/></section>{r.sessions.loading?<LoadingBlock label="Loading class sessions…"/>:r.sessions.error?<ErrorBlock message={r.sessions.error} onRetry={r.sessions.refetch}/>:<div className="grid items-start gap-5 lg:grid-cols-[300px_minmax(0,1fr)]"><AttendanceSessionList sessions={r.sessions.data??[]} id={r.id} onPick={r.pick} disabled={r.saving}/>{!r.id?<section className="card border border-base-300 bg-base-100 p-10"><EmptyBlock title="Choose a class session" hint="View and mark its students."/></section>:r.roster.loading||r.roster.stale?<LoadingBlock label="Loading student register…"/>:r.roster.error?<ErrorBlock message={r.roster.error} onRetry={r.roster.refetch}/>:r.selected?<AttendanceRegister key={r.id} session={r.selected} rows={r.rows} draft={r.draft} editable={r.editable} saving={r.saving} error={r.error} saved={r.saved} change={r.change} discard={r.discard} save={r.save}/>:<EmptyBlock title="Session unavailable" hint="Choose a session you have permission to manage."/>}</div>}</div>;
}
