export const staffAccounts = [
  {
    email: "admin@sparch.rw",
    firstName: "System",
    lastName: "Administrator",
    role: "SUPER_ADMIN",
    password: "Admin123!",
  },
  {
    email: "academic@sparch.rw",
    firstName: "Aline",
    lastName: "Mukamurenzi",
    role: "ACADEMIC_ADMIN",
    password: "Academic123!",
  },
  {
    email: "finance@sparch.rw",
    firstName: "David",
    lastName: "Rugamba",
    role: "FINANCE_ADMIN",
    password: "Finance123!",
  },
  {
    email: "clarisse@sparch.rw",
    firstName: "Clarisse",
    lastName: "Uwase",
    role: "TEACHER",
    password: "Teacher123!",
  },
  {
    email: "nadine@sparch.rw",
    firstName: "Nadine",
    lastName: "Mukamana",
    role: "TEACHER",
    password: "Teacher123!",
  },
  {
    email: "jeanpaul@sparch.rw",
    firstName: "Jean-Paul",
    lastName: "Habimana",
    role: "TEACHER",
    password: "Teacher123!",
  },
  {
    email: "aline@sparch.rw",
    firstName: "Aline",
    lastName: "Uwimana",
    role: "TEACHER",
    password: "Teacher123!",
  },
  {
    email: "eric@sparch.rw",
    firstName: "Eric",
    lastName: "Nshuti",
    role: "TEACHER",
    password: "Teacher123!",
  },
  {
    email: "yves@sparch.rw",
    firstName: "Yves",
    lastName: "Kagabo",
    role: "TEACHER",
    password: "Teacher123!",
  },
] as const;
