import type { StudentSeed } from './base-student-seed.js';
export const studentSeeds: StudentSeed[] = [
  {
    code: "SDR-2024-0203",
    firstName: "Diane",
    lastName: "Umutoni",
    email: "diane@student.sparch.rw",
    phone: "+250 788 100 203",
    levelCode: "A1",
    intakeCode: "INTAKE-2026-09",
    shift: "MORNING",
    accountStatus: "PENDING",
    enrollmentStatus: "ACTIVE",
    fee: 45000,
    paid: 0,
    refund: 0,
    discount: 0,
    methodCode: "BANK",
    dueInDays: -14,
  },
  {
    code: "SDR-2024-0301",
    firstName: "Nella",
    lastName: "Ishimwe",
    email: "nella@student.sparch.rw",
    phone: "+250 788 100 301",
    levelCode: "A1",
    intakeCode: "INTAKE-2026-09",
    shift: "EVENING",
    accountStatus: "ACTIVE",
    enrollmentStatus: "ACTIVE",
    fee: 45000,
    paid: 20000,
    refund: 0,
    discount: 0,
    methodCode: "MOMO",
    dueInDays: 14,
  },
];
