import type { DemoStudentSeed } from './demo-demo-student-seed.js';
export const demoStudentSeeds: DemoStudentSeed[] = [
  {
    code: "SDR-2024-0142",
    firstName: "Sandrine",
    lastName: "Ineza",
    email: "sandrine@student.sparch.rw",
    phone: "+250 788 100 142",
    levelCode: "A2",
    intakeCode: "INTAKE-2024-07",
    shift: "EVENING",
    accountStatus: "ACTIVE",
    enrollmentStatus: "COMPLETED",
    fee: 45000,
    paid: 45000,
    refund: 0,
    discount: 0,
    methodCode: "MOMO",
    dueInDays: -30,
  },
  {
    code: "SDR-2024-0187",
    firstName: "Patrick",
    lastName: "Mugenzi",
    email: "patrick@student.sparch.rw",
    phone: "+250 788 100 187",
    levelCode: "B1-BERUF",
    intakeCode: "INTAKE-2026-09",
    shift: "EVENING",
    accountStatus: "ACTIVE",
    enrollmentStatus: "ACTIVE",
    fee: 60000,
    paid: 30000,
    refund: 0,
    discount: 0,
    methodCode: "AIRTEL",
    dueInDays: 21,
  },
  {
    code: "SDR-2024-0211",
    firstName: "Fabrice",
    lastName: "Rwigema",
    email: "fabrice@student.sparch.rw",
    phone: "+250 788 100 211",
    levelCode: "B2-TESTDAF",
    intakeCode: "INTAKE-2026-09",
    shift: "WEEKEND",
    accountStatus: "ACTIVE",
    enrollmentStatus: "ACTIVE",
    fee: 70000,
    paid: 70000,
    refund: 0,
    discount: 0,
    methodCode: "CARD",
    dueInDays: -60,
  },
  {
    code: "SDR-2024-0234",
    firstName: "Solange",
    lastName: "Nyirahabimana",
    email: "solange@student.sparch.rw",
    phone: "+250 788 100 234",
    levelCode: "B2",
    intakeCode: "INTAKE-2024-07",
    shift: "EVENING",
    accountStatus: "GRADUATED",
    enrollmentStatus: "COMPLETED",
    fee: 65000,
    paid: 0,
    refund: 0,
    discount: 65000,
    methodCode: "SCHOLARSHIP",
    dueInDays: -120,
  },
  {
    code: "SDR-2024-0255",
    firstName: "Emmanuel",
    lastName: "Butera",
    email: "emmanuel@student.sparch.rw",
    phone: "+250 788 100 255",
    levelCode: "B1",
    intakeCode: "INTAKE-2026-01",
    shift: "AFTERNOON",
    accountStatus: "SUSPENDED",
    enrollmentStatus: "WITHDRAWN",
    fee: 55000,
    paid: 55000,
    refund: 55000,
    discount: 0,
    methodCode: "MOMO",
    dueInDays: -200,
  },
];
