import { dateLabel,statusLabels } from '../homework/format';
import type { RosterStudent,Submission } from '../homework/types';
export type ReviewRow = { student: RosterStudent; submission?: Submission };
type Props = { rows: ReviewRow[]; selected: string | null; onSelect: (id: string) => void; busy: boolean; table?: boolean; maxPoints: string | number };
export function AssignmentRoster({ rows, selected, onSelect, busy, table, maxPoints }: Props) {
  if (!rows.length) return <p className="p-6 text-center text-sm text-muted">No students match these filters.</p>;
  if (table) return <div className="overflow-x-auto"><table className="table table-sm"><thead><tr><th>Student</th><th>Status</th><th>Submitted</th><th>Score</th><th><span className="sr-only">Review</span></th></tr></thead><tbody>{rows.map(({ student: r, submission: s }) => <tr key={r.id}><td><p className="font-semibold">{r.user.firstName} {r.user.lastName}</p><p className="mt-1 text-xs text-muted">{r.studentCode}</p></td><td>{s?.revision ? statusLabels[s.status] : 'Not submitted'}{s?.versions?.[0]?.isLate ? <span className="badge badge-warning badge-soft badge-xs ml-2">Late</span> : null}</td><td className="whitespace-nowrap">{s?.submittedAt ? dateLabel(s.submittedAt, true) : '—'}</td><td className="whitespace-nowrap">{s?.status === 'GRADED' ? `${s.score}/${maxPoints}` : '—'}</td><td>{s?.revision ? <button className="btn btn-ghost btn-xs" disabled={busy} onClick={() => onSelect(s.id)}>View work</button> : null}</td></tr>)}</tbody></table></div>;
  return <div className="max-h-[65vh] overflow-y-auto">{rows.map(({ student: r, submission: s }) => <button type="button" key={r.id} disabled={!s?.revision || busy} aria-pressed={s?.id === selected} className={`w-full border-t border-base-300 p-4 text-left ${s?.id === selected ? 'border-l-2 border-l-primary bg-primary text-primary-content' : 'hover:bg-base-200'} disabled:opacity-60`} onClick={() => s && onSelect(s.id)}><span className="block text-xs font-semibold">{r.user.firstName} {r.user.lastName}</span><span className="mt-1 block text-[11px] text-muted">{s?.revision ? statusLabels[s.status] : 'Not submitted'}{s?.versions?.[0]?.isLate ? ' · Late' : ''}{s?.status === 'GRADED' ? ` · ${s.score}/${maxPoints}` : ''}</span></button>)}</div>;
}
