import type { FormEvent } from 'react';
import { useState } from 'react';
import { FiArrowLeft,FiSave } from 'react-icons/fi';
import { useApi } from '../../../hooks/useApi';
import { apiErrorMessage } from '../../../lib/api';
import { getHomeworkRoster,saveHomework } from '../../../lib/homework';
import { listClasses } from '../../../lib/services';
import { questionError } from '../../questions/validate';
import { QuestionBuilder } from '../../questions/QuestionBuilder';
import type { Homework,HomeworkInput } from '../homework/types';
import { EditorExtras } from './EditorExtras';
const empty = (classGroupId = ''): HomeworkInput => ({ classGroupId, title: '', instructions: '', responseType: 'TEXT', status: 'DRAFT', dueAt: null, releaseAt: null, estimatedMinutes: 20, maxPoints: 10, allowLate: true, maxSubmissions: 3, resources: [], rubric: [], studentIds: [], questions: [] });
const localDate = (v: string | null) => v ? new Date(new Date(v).getTime() - new Date(v).getTimezoneOffset() * 60000).toISOString().slice(0, 16) : '';
export function AssignmentEditor({ assignment, onClose, onSaved }: { assignment?: Homework; onClose: () => void; onSaved: (id: string) => void }) {
  const classes = useApi('assignment-classes', listClasses);
  const [value, setValue] = useState<HomeworkInput>(() => assignment ? { ...assignment, maxPoints: Number(assignment.maxPoints), studentIds: assignment.recipients.map(r => r.studentId), questions: (assignment.questions ?? []).map(q => ({ ...q.question, points: Number(q.points ?? q.question.points), correctAnswer: q.question.correctAnswer ?? null })) } : empty());
  const [mode, setMode] = useState<'response' | 'questions'>(assignment?.questions?.length ? 'questions' : 'response');
  const [busy, setBusy] = useState(false), [error, setError] = useState('');
  const rosterData = useApi(`assignment-roster-${value.classGroupId}`, () => getHomeworkRoster(value.classGroupId), !!value.classGroupId);
  const hasSubmitted = assignment?.submissions?.some(s => s.revision > 0) ?? false;
  const roster = rosterData.data ?? [];
  function field<K extends keyof HomeworkInput>(key: K, v: HomeworkInput[K]) { setValue(p => ({ ...p, [key]: v })); }
  async function submit(e: FormEvent) {
    e.preventDefault();
    const issue = questionError(value.questions); if (issue) { setError(issue); return; }
    setBusy(true); setError('');
    try { const saved = await saveHomework(value, assignment?.id); onSaved(saved.id); }
    catch (err) { setError(apiErrorMessage(err, 'Could not save assignment.')); }
    finally { setBusy(false); }
  }
  return <form onSubmit={e => void submit(e)} className="space-y-5"><button type="button" className="btn btn-ghost btn-sm" disabled={busy} onClick={onClose}><FiArrowLeft />Back to assignments</button>
    <section className="card border border-base-300/70 bg-base-100 p-6 sm:p-8"><p className="text-[10px] font-semibold uppercase tracking-[.2em] text-primary">Prepare · guide · encourage</p><h1 className="mt-3 text-2xl font-bold">{assignment ? 'Edit assignment' : 'Create assignment'}</h1><p className="mt-2 text-sm leading-7 text-base-content/60">Tell students what to do, what to submit, and what success looks like. Save as a draft until you’re ready.</p></section>
    <div className="grid items-start gap-5 lg:grid-cols-[minmax(0,1fr)_320px]"><section className="card min-w-0 space-y-5 border border-base-300/70 bg-base-100 p-5 sm:p-7">
      <label className="block"><span className="mb-2 block text-xs font-semibold">Class *</span><select required className="select w-full" value={value.classGroupId} disabled={!!assignment} onChange={e => { const classGroupId = e.target.value; setValue(p => ({ ...p, classGroupId, studentIds: [], questions: [], maxPoints: 10 })); }}><option value="">Choose a class</option>{classes.data?.map(c => <option key={c.id} value={c.id}>{c.name} · {c.level.code}</option>)}</select>{classes.error ? <p className="text-xs text-error">{classes.error}</p> : null}</label>
      <label className="block"><span className="mb-2 block text-xs font-semibold">Assignment title *</span><input required minLength={3} maxLength={160} className="input w-full" placeholder="e.g. Introduce yourself in German" value={value.title} onChange={e => field('title', e.target.value)} /></label>
      <label className="block"><span className="mb-2 block text-xs font-semibold">Instructions *</span>{hasSubmitted ? <p className="mb-2 text-xs text-base-content/55">Instructions stay fixed after submission. You can still extend deadlines and submission limits.</p> : null}<textarea disabled={hasSubmitted} required minLength={10} maxLength={20000} rows={9} className="textarea w-full text-sm leading-7" placeholder={'Your goal: …\n\n1. Prepare …\n2. Write or record …\n3. Check …\n\nSubmit: …'} value={value.instructions} onChange={e => field('instructions', e.target.value)} /><span className="mt-2 block text-[10px] text-base-content/50">Use short steps, examples and a clear expected length.</span></label>
      <fieldset disabled={hasSubmitted} className="space-y-2"><legend className="mb-2 text-xs font-semibold">How will students respond?</legend><div className="grid gap-3 sm:grid-cols-2">{[{ value: 'response' as const, label: 'Written, audio or file task', hint: 'Open-ended work with optional grading rubric.' }, { value: 'questions' as const, label: 'Write questions', hint: 'Multiple choice and written answers, created here.' }].map(option => <label key={option.value} className={`flex cursor-pointer gap-3 rounded-box border p-4 ${mode === option.value ? 'border-primary bg-primary/5' : 'border-base-300'}`}><input type="radio" name="assignment-mode" className="radio radio-primary radio-sm" checked={mode === option.value} onChange={() => { setMode(option.value); setValue(p => ({ ...p, questions: [], rubric: [], maxPoints: 10, responseType: 'TEXT' })); }} /><span><span className="block text-sm font-semibold">{option.label}</span><span className="mt-1 block text-xs leading-5 text-base-content/60">{option.hint}</span></span></label>)}</div></fieldset>
      {mode === 'questions' ? <QuestionBuilder value={value.questions} locked={hasSubmitted} onChange={questions => setValue(p => ({ ...p, questions, maxPoints: questions.reduce((sum, q) => sum + q.points, 0) }))} /> : null}
      <div className="grid gap-4 sm:grid-cols-2"><label><span className="mb-2 block text-xs font-semibold">Response format</span><select disabled={hasSubmitted || mode === 'questions'} className="select w-full" value={value.responseType} onChange={e => field('responseType', e.target.value as HomeworkInput['responseType'])}><option value="TEXT">Written response</option><option value="FILE">File upload</option><option value="AUDIO">Audio recording</option><option value="MIXED">Text or attachment</option></select></label><label><span className="mb-2 block text-xs font-semibold">Estimated effort (minutes)</span><input required type="number" min={1} max={600} className="input w-full" value={value.estimatedMinutes} onChange={e => field('estimatedMinutes', Number(e.target.value))} /></label></div>
      {rosterData.error ? <p role="alert" className="text-xs text-error">Could not load recipients: {rosterData.error}</p> : null}<EditorExtras questionBased={mode === 'questions'} locked={hasSubmitted} value={value} onChange={setValue} roster={roster} />
    </section><aside className="card space-y-5 border border-base-300/70 bg-base-100 p-5"><h2 className="font-semibold">Schedule & expectations</h2>{[{ key: 'releaseAt' as const, label: 'Available from' }, { key: 'dueAt' as const, label: 'Due date' }].map(({ key, label }) => <label key={key}><span className="mb-2 block text-xs font-semibold">{label} · your local time</span><input type="datetime-local" className="input w-full text-xs" value={localDate(value[key])} onChange={e => field(key, e.target.value ? new Date(e.target.value).toISOString() : null)} /></label>)}<label><span className="mb-2 block text-xs font-semibold">Total points</span><input disabled={hasSubmitted || mode === 'questions'} required type="number" min="0.01" max={1000} step="0.01" className="input w-full" value={value.maxPoints} onChange={e => field('maxPoints', Number(e.target.value))} /></label><label><span className="mb-2 block text-xs font-semibold">Maximum submissions</span><input required type="number" min={1} max={20} className="input w-full" value={value.maxSubmissions} onChange={e => field('maxSubmissions', Number(e.target.value))} /></label><label className="flex items-center gap-3 text-xs"><input type="checkbox" className="checkbox checkbox-sm" checked={value.allowLate} onChange={e => field('allowLate', e.target.checked)} />Accept late work</label><label><span className="mb-2 block text-xs font-semibold">Visibility</span><select className="select w-full" value={value.status} onChange={e => field('status', e.target.value as HomeworkInput['status'])}><option value="DRAFT">Draft · only staff</option><option value="PUBLISHED">Published · assigned students</option>{assignment ? <option value="ARCHIVED">Archived · hidden from students</option> : null}</select></label><p className="text-xs leading-6 text-base-content/60">Published tasks appear at the release time. Homework is untimed: students can save and return. After submission, you can request a revision.</p>{error ? <p role="alert" className="alert alert-error alert-soft text-xs">{error}</p> : null}<button className="btn btn-primary rounded-full" disabled={busy || classes.loading || rosterData.loading || !!rosterData.error || mode === 'questions' && !value.questions.length}><FiSave />{busy ? 'Saving…' : value.status === 'PUBLISHED' ? 'Save & publish' : 'Save assignment'}</button></aside></div>
  </form>;
}
