import { FiPlus,FiX } from 'react-icons/fi';
import type { HomeworkInput,RosterStudent } from '../homework/types';
export function EditorExtras({ value, onChange, roster, locked, questionBased }: { value: HomeworkInput; onChange: (value: HomeworkInput) => void; roster: RosterStudent[]; locked?: boolean; questionBased?: boolean }) {
  return <div className="space-y-6">
    <section><h3 className="text-sm font-semibold">Who should complete it?</h3><p className="mb-3 mt-1 text-xs text-base-content/60">Leave everyone unselected to assign the whole class.</p><div className="max-h-36 space-y-2 overflow-y-auto rounded-field border border-base-300 p-3">{roster.length ? roster.map(s => <label key={s.id} className="flex items-center gap-3 text-xs"><input type="checkbox" disabled={locked} className="checkbox checkbox-xs" checked={value.studentIds.includes(s.id)} onChange={e => onChange({ ...value, studentIds: e.target.checked ? [...value.studentIds, s.id] : value.studentIds.filter(id => id !== s.id) })} />{s.user.firstName} {s.user.lastName}<span className="text-base-content/40">{s.studentCode}</span></label>) : <p className="text-xs text-base-content/50">Choose a class to load its students.</p>}</div></section>
    <section><div className="mb-3 flex items-center justify-between"><h3 className="text-sm font-semibold">Helpful links</h3><button type="button" className="btn btn-ghost btn-xs" disabled={value.resources.length >= 10} onClick={() => onChange({ ...value, resources: [...value.resources, { title: '', url: '' }] })}><FiPlus />Add link</button></div>{value.resources.map((r, i) => <div key={i} className="mb-2 flex flex-wrap gap-2"><input aria-label={`Resource ${i + 1} title`} required className="input input-sm min-w-0 flex-1" placeholder="Resource title" value={r.title} onChange={e => onChange({ ...value, resources: value.resources.map((v, n) => n === i ? { ...v, title: e.target.value } : v) })} /><input aria-label={`Resource ${i + 1} URL`} required type="url" className="input input-sm min-w-0 flex-1" placeholder="https://…" value={r.url} onChange={e => onChange({ ...value, resources: value.resources.map((v, n) => n === i ? { ...v, url: e.target.value } : v) })} /><button type="button" aria-label={`Remove resource ${i + 1}`} className="btn btn-ghost btn-sm" onClick={() => onChange({ ...value, resources: value.resources.filter((_, n) => n !== i) })}><FiX /></button></div>)}</section>
    {!questionBased ? <section><div className="mb-2 flex items-center justify-between"><h3 className="text-sm font-semibold">Grading rubric</h3><button type="button" className="btn btn-ghost btn-xs" disabled={locked || value.rubric.length >= 10} onClick={() => onChange({ ...value, rubric: [...value.rubric, { title: '', description: '', points: 1 }] })}><FiPlus />Add criterion</button></div><p className="mb-3 text-xs text-base-content/60">Optional. Criteria points must add up to {value.maxPoints}. Students see this before they start.</p>{value.rubric.map((r, i) => <div key={i} className="mb-3 space-y-2 rounded-box border border-base-300 p-3"><div className="flex gap-2"><input disabled={locked} required aria-label={`Criterion ${i + 1} title`} className="input input-sm min-w-0 flex-1" placeholder="e.g. Vocabulary" value={r.title} onChange={e => onChange({ ...value, rubric: value.rubric.map((v, n) => n === i ? { ...v, title: e.target.value } : v) })} /><input disabled={locked} required aria-label={`Criterion ${i + 1} points`} type="number" min="0.01" step="0.01" max="1000" className="input input-sm w-20" value={r.points} onChange={e => onChange({ ...value, rubric: value.rubric.map((v, n) => n === i ? { ...v, points: Number(e.target.value) } : v) })} /><button type="button" disabled={locked} aria-label={`Remove criterion ${i + 1}`} className="btn btn-ghost btn-sm" onClick={() => onChange({ ...value, rubric: value.rubric.filter((_, n) => n !== i) })}><FiX /></button></div><input disabled={locked} aria-label={`Criterion ${i + 1} description`} className="input input-sm w-full" placeholder="What does a good response demonstrate?" value={r.description} onChange={e => onChange({ ...value, rubric: value.rubric.map((v, n) => n === i ? { ...v, description: e.target.value } : v) })} /></div>)}</section> : null}
  </div>;
}
