import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { unlink } from 'node:fs/promises';
import request from 'supertest';
import type { Response } from 'supertest';
import { createApp } from '../app.js';
import { env } from '../config/env.js';
import { assertLevelAccess } from '../lib/access.js';
import { signAccessToken } from '../lib/jwt.js';
import { prisma } from '../lib/prisma.js';
import { registerStudent } from '../modules/auth/register-student.js';
import { createPayment } from '../modules/payments/payment-commands.js';
import { safeFilePath } from '../modules/uploads/uploads.service.js';
assert.match(env.DATABASE_URL, /@(localhost|127\.0\.0\.1):/, 'Use only the local fixture database');
const stamp = `course-photo-${randomUUID()}`;
const app = createApp();
type Payload = { id: string; defaultFee: string; totalFee?: string; avatarUrl: string; user: { avatarUrl: string } };
const payload = (response: Response): Payload => (response.body as { data: Payload }).data;
const userIds: string[] = [], studentIds: string[] = [], levelIds: string[] = [], files: string[] = [];
let repeatIntakeId: string | undefined;
let campusId: string | undefined, intakeId: string | undefined, methodId: string | undefined;
const png = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jp1sAAAAASUVORK5CYII=', 'base64');
try {
  const academic = await prisma.user.create({ data: { email: `${stamp}@test.local`, firstName: 'Test', lastName: 'Academic', role: 'ACADEMIC_ADMIN', status: 'ACTIVE', passwordHash: 'unused' } });
  userIds.push(academic.id);
  const academicToken = signAccessToken(academic.id, academic.email, academic.role);
  const campus = await prisma.campus.create({ data: { code: stamp, name: stamp } }); campusId = campus.id;
  const intake = await prisma.intake.create({ data: { code: stamp, name: stamp, startDate: new Date(), endDate: new Date(Date.now() + 86400000 * 30) } }); intakeId = intake.id;
  for (let i = 0; i < 2; i++) {
    const response: Response = await request(app).post('/api/levels').set('Authorization', `Bearer ${academicToken}`).send({ code: `CP-${stamp.slice(-8)}-${i}`, title: 'Fixture Course', levelLabel: 'A1', defaultFee: i ? 5678 : 1234 });
    assert.equal(response.status, 201); levelIds.push(payload(response).id);
    assert.equal(payload(response).defaultFee, String(i ? 5678 : 1234));
  }
  await request(app).post('/api/intakes').set('Authorization', `Bearer ${academicToken}`).send({ code: 'EMPTY', name: 'Empty intake', startDate: new Date(), endDate: new Date(Date.now() + 86400000) }).expect(400);
  await request(app).patch(`/api/intakes/${intakeId}`).set('Authorization', `Bearer ${academicToken}`).send({ levelIds: [] }).expect(400);
  await prisma.intake.update({ where: { id: intakeId }, data: { levels: { connect: levelIds.map(id => ({ id })) } } });
  const registered = await registerStudent({ firstName: 'Test', lastName: 'Student', email: `${stamp}-student@test.local`, password: 'TestPassword123!', campusId, intakeId, intendedLevelId: levelIds[0], shift: 'EVENING' }, {});
  userIds.push(registered.user.id);
  const student = await prisma.student.findUniqueOrThrow({ where: { userId: registered.user.id } }); studentIds.push(student.id);
  assert.equal(student.intakeId, intakeId);
  assert.equal(await prisma.enrollment.count({ where: { studentId: student.id } }), 1);
  assert.equal(await prisma.charge.count({ where: { studentId: student.id, type: { in: ['REGISTRATION', 'BOOKS'] } } }), 0);
  await assert.rejects(assertLevelAccess(registered.user.id, levelIds[0]), /payment/);
  for (const levelId of levelIds.slice(1)) {
    const response: Response = await request(app).post('/api/enrollments').set('Authorization', `Bearer ${academicToken}`).send({ studentId: student.id, levelId, intakeId });
    assert.equal(response.status, 201); assert.equal(payload(response).totalFee, undefined);
  }
  const studentToken = signAccessToken(registered.user.id, registered.user.email, 'STUDENT');
  await request(app).post('/api/enrollments/join').set('Authorization', `Bearer ${studentToken}`).send({ intakeId, levelId: levelIds[0], totalFee: 0 }).expect(400);
  await request(app).post('/api/enrollments/join').set('Authorization', `Bearer ${studentToken}`).send({ intakeId, levelId: levelIds[0] }).expect(409);
  const module = await prisma.module.create({ data: { levelId: levelIds[0], title: 'Paid fixture module', order: 0, isPublished: true } });
  const lesson = await prisma.lesson.create({ data: { moduleId: module.id, title: 'Paid fixture lesson', order: 0, isPublished: true, body: 'Protected course content' } });
  await request(app).get(`/api/content/my/lessons/${lesson.id}`).set('Authorization', `Bearer ${studentToken}`).expect(403);
  await request(app).get(`/api/content/my/levels/${levelIds[0]}/coursebook`).set('Authorization', `Bearer ${studentToken}`).expect(403);
  const first = await prisma.enrollment.findFirstOrThrow({ where: { studentId: student.id, levelId: levelIds[0] } });
  assert.equal(first.totalFee.toString(), '1234');
  const changed = await request(app).patch(`/api/levels/${levelIds[0]}`).set('Authorization', `Bearer ${academicToken}`).send({ defaultFee: 4321 });
  assert.equal(changed.status, 200); assert.equal(payload(changed).defaultFee, '4321');
  assert.equal((await prisma.enrollment.findUniqueOrThrow({ where: { id: first.id } })).totalFee.toString(), '1234');
  const next = await registerStudent({ firstName: 'New', lastName: 'Student', email: `${stamp}-next@test.local`, password: 'TestPassword123!', campusId, intakeId, intendedLevelId: levelIds[0], shift: 'EVENING' }, {});
  userIds.push(next.user.id); const nextStudent = await prisma.student.findUniqueOrThrow({ where: { userId: next.user.id } }); studentIds.push(nextStudent.id);
  assert.equal((await prisma.enrollment.findFirstOrThrow({ where: { studentId: nextStudent.id } })).totalFee.toString(), '4321');
  await request(app).patch(`/api/enrollments/${first.id}`).set('Authorization', `Bearer ${academicToken}`).send({ totalFee: 0 }).expect(403);
  await request(app).get('/api/payments').set('Authorization', `Bearer ${academicToken}`).expect(403);
  await assert.rejects(assertLevelAccess(registered.user.id, levelIds[0]), /payment/);
  const method = await prisma.paymentMethodConfig.create({ data: { code: stamp, name: 'Local fixture only' } }); methodId = method.id;
  await createPayment({ studentId: student.id, amount: 1233, methodId, reference: undefined, notes: undefined });
  await assert.rejects(assertLevelAccess(registered.user.id, levelIds[0]), /payment/);
  await request(app).get(`/api/content/my/lessons/${lesson.id}`).set('Authorization', `Bearer ${studentToken}`).expect(403);
  await createPayment({ studentId: student.id, amount: 1, methodId, reference: undefined, notes: undefined });
  await assertLevelAccess(registered.user.id, levelIds[0]);
  await request(app).get(`/api/content/my/lessons/${lesson.id}`).set('Authorization', `Bearer ${studentToken}`).expect(200);
  await assert.rejects(assertLevelAccess(registered.user.id, levelIds[1]), /payment/);
  const repeatIntake = await prisma.intake.create({ data: { code: `${stamp}-repeat`, name: 'Repeat fixture', startDate: new Date(), endDate: new Date(Date.now() + 86400000 * 30), levels: { connect: { id: levelIds[0] } } } });
  repeatIntakeId = repeatIntake.id;
  await request(app).post('/api/enrollments/join').set('Authorization', `Bearer ${studentToken}`).send({ intakeId: repeatIntakeId, levelId: levelIds[0] }).expect(201);
  await assert.rejects(assertLevelAccess(registered.user.id, levelIds[0]), /payment/);
  await request(app).get(`/api/content/my/lessons/${lesson.id}`).set('Authorization', `Bearer ${studentToken}`).expect(403);
  const token = signAccessToken(registered.user.id, registered.user.email, 'STUDENT');
  await request(app).post('/api/uploads').set('Authorization', `Bearer ${token}`).attach('file', png, 'photo.png').expect(403);
  await request(app).post('/api/uploads/avatar').set('Authorization', `Bearer ${token}`).attach('file', Buffer.from('<svg/>'), { filename: 'fake.png', contentType: 'image/png' }).expect(400);
  await request(app).post('/api/uploads/avatar').set('Authorization', `Bearer ${token}`).attach('file', Buffer.alloc(5 * 1024 * 1024 + 1), 'large.png').expect(400);
  let previous: string | null = null;
  for (let i = 0; i < 2; i++) {
    const photo = await request(app).post('/api/uploads/avatar').set('Authorization', `Bearer ${token}`).attach('file', png, 'photo.png');
    assert.equal(photo.status, 201); const url = payload(photo).avatarUrl; files.push(url.split('/').pop()!);
    await request(app).get(url).expect('Content-Type', /image\/png/).expect(200);
    if (previous) await request(app).get(previous).expect(404);
    await request(app).patch('/api/auth/me').set('Authorization', `Bearer ${academicToken}`).send({ avatarUrl: url }).expect(400);
    const me = await request(app).get('/api/auth/me').set('Authorization', `Bearer ${token}`); assert.equal(payload(me).user.avatarUrl, url);
    previous = url;
  }
  await request(app).patch('/api/auth/me').set('Authorization', `Bearer ${token}`).send({ avatarUrl: null }).expect(200);
  await request(app).get(previous!).expect(404);
  process.stdout.write('Course/photo integration passed: intake membership, academic pricing, enrolled-price snapshots, dynamic charges, partial/full course unlock, role isolation, photo upload/replacement/removal and ownership. No real payment requests.\n');
} finally {
  await prisma.auditLog.deleteMany({ where: { OR: [{ actorId: { in: userIds } }, { entityId: { in: [...userIds, ...levelIds] } }] } });
  await prisma.activityEvent.deleteMany({ where: { studentId: { in: studentIds } } });
  await prisma.notificationDelivery.deleteMany({ where: { userId: { in: userIds } } });
  await prisma.student.deleteMany({ where: { id: { in: studentIds } } });
  await prisma.uploadedFile.deleteMany({ where: { uploaderId: { in: userIds } } });
  await prisma.user.deleteMany({ where: { id: { in: userIds } } });
  await prisma.level.deleteMany({ where: { id: { in: levelIds } } });
  if (methodId) await prisma.paymentMethodConfig.delete({ where: { id: methodId } });
  if (repeatIntakeId) await prisma.intake.delete({ where: { id: repeatIntakeId } });
  if (intakeId) await prisma.intake.delete({ where: { id: intakeId } });
  if (campusId) await prisma.campus.delete({ where: { id: campusId } });
  for (const name of files) await unlink(safeFilePath(name)!).catch(() => undefined);
  await prisma.$disconnect();
}
