import { FiMessageCircle,FiSearch,FiX } from 'react-icons/fi';
import type { Conversation } from '../../lib/services';
import { EmptyBlock,ErrorBlock,LoadingBlock } from '../common/PageState';
import { accentFor,dedupeParticipants,initials,relativeTime,snippet,threadTitle } from './utils';
type Props = { threads: Conversation[]; loading: boolean; error: string | null; onRetry: () => void; selectedId: string | null; onPick: (id: string) => void; myId: string | null | undefined; search: string; onSearch: (v: string) => void; filter: 'all' | 'unread'; onFilter: (v: 'all' | 'unread') => void; onCompose: () => void };
export function ConversationList({ threads, loading, error, onRetry, selectedId, onPick, myId, search, onSearch, filter, onFilter, onCompose }: Props) {
  const unread = threads.filter(t => t.unreadCount > 0).length;
  const filtered = threads.filter(t => (filter !== 'unread' || t.unreadCount > 0) && (!search.trim() || `${threadTitle(t,myId)} ${t.messages[0]?.body ?? ''}`.toLowerCase().includes(search.trim().toLowerCase())));
  return <div className="flex h-full min-h-0 flex-col"><div className="p-5"><div className="flex items-center justify-between"><h2 className="text-sm font-semibold">Messages</h2><span className="text-xs text-muted">{threads.length} chats</span></div><label className="input input-sm mt-4 flex w-full items-center gap-2"><FiSearch aria-hidden className="shrink-0 opacity-50" /><input aria-label="Search conversations" value={search} onChange={e=>onSearch(e.target.value)} placeholder="Find a conversation" className="min-w-0 grow" />{search ? <button aria-label="Clear conversation search" type="button" onClick={()=>onSearch('')} className="btn btn-xs btn-ghost btn-circle"><FiX aria-hidden /></button> : null}</label><div className="mt-3 flex gap-2">{(['all','unread'] as const).map(v=><button key={v} onClick={()=>onFilter(v)} aria-pressed={filter===v} className={`btn btn-xs rounded-full ${filter===v?'btn-neutral':'btn-ghost'}`}>{v==='all'?'All conversations':`Unread · ${unread}`}</button>)}</div></div>
    <div className="min-h-0 flex-1 overflow-y-auto px-3 pb-3">{loading ? <LoadingBlock label="Loading conversations…" /> : error ? <ErrorBlock message={error} onRetry={onRetry} /> : !filtered.length ? <div className="py-8 text-center"><FiMessageCircle aria-hidden size={28} className="mx-auto text-muted" /><EmptyBlock title={threads.length ? 'No matching conversations' : 'Your conversations start here'} hint={threads.length ? 'Try another search or view all chats.' : 'Reach out to a teacher or someone in your class.'} />{!threads.length ? <button onClick={onCompose} className="btn btn-sm mt-3">Start a conversation</button> : <button onClick={()=>{onSearch('');onFilter('all');}} className="btn btn-sm mt-3">Show all conversations</button>}</div> : <ul className="space-y-1">{filtered.map(t=>{
      const title=threadTitle(t,myId),last=t.messages[0],others=dedupeParticipants(t.participants).filter(p=>p.user.id!==myId),person=others[0]?.user,active=selectedId===t.id;
      return <li key={t.id}><button onClick={()=>onPick(t.id)} aria-current={active?'true':undefined} className={`flex w-full items-start gap-3 rounded-2xl p-4 text-left transition-colors ${active?'bg-neutral text-neutral-content':'hover:bg-base-200'}`}><span className={`grid size-11 shrink-0 place-items-center rounded-2xl text-xs font-semibold ${person?accentFor(person.firstName):'bg-base-200 text-base-content'}`}>{person?initials(person.firstName,person.lastName):'Me'}</span><span className="min-w-0 flex-1"><span className="flex items-center justify-between gap-2"><span className="truncate text-sm font-semibold">{title}</span>{t.unreadCount>0?<span aria-label={`${t.unreadCount} unread messages`} className="grid min-w-5 place-items-center rounded-full bg-primary px-1.5 text-[10px] text-primary-content">{t.unreadCount}</span>:null}</span><span className={`mt-1 block truncate text-xs ${active?'text-neutral-content':'text-muted'}`}>{last?`${last.senderId===myId?'You':last.sender.firstName}: ${snippet(last.body,60)}`:'Say hello to start chatting'}</span><span className={`mt-2 block text-[10px] ${active?'text-neutral-content':'text-muted'}`}>{others.length>1?'Group conversation · ':''}{relativeTime(t.updatedAt)}</span></span></button></li>;
    })}</ul>}</div></div>;
}
