import { format,isToday,isYesterday,parseISO } from 'date-fns';
import { useEffect,useMemo,useRef } from 'react';
import { FiArrowLeft,FiMessageCircle } from 'react-icons/fi';
import type { ChatMessage,Conversation } from '../../lib/services';
import { ErrorBlock,LoadingBlock } from '../common/PageState';
import { MessageComposer } from './MessageComposer';
import { accentFor,dedupeParticipants,initials,threadTitle } from './utils';
type Props = { thread: Conversation | null; messages: ChatMessage[]; loading: boolean; error: string | null; onRetry: () => void; myId: string | null | undefined; draft: string; onDraft: (v: string) => void; onSend: () => void; sending: boolean; chatError: string | null; onBack?: () => void };
function dayLabel(iso:string){const d=parseISO(iso);return isToday(d)?'Today':isYesterday(d)?'Yesterday':format(d,'d MMM yyyy');}
export function MessageView({ thread, messages, loading, error, onRetry, myId, draft, onDraft, onSend, sending, chatError, onBack }:Props) {
  const list=useRef<HTMLUListElement>(null),nearBottom=useRef(true),lastThread=useRef<string|undefined>(undefined);
  const last=messages[messages.length-1];
  useEffect(()=>{const changed=lastThread.current!==thread?.id;if(list.current&&(changed||nearBottom.current||last?.senderId===myId))list.current.scrollTop=list.current.scrollHeight;lastThread.current=thread?.id;},[thread?.id,last?.id,last?.senderId,myId,loading]);
  const grouped=useMemo(()=>{const out:{label:string;items:ChatMessage[]}[]=[];for(const m of messages){const label=dayLabel(m.createdAt);if(out.at(-1)?.label!==label)out.push({label,items:[m]});else out.at(-1)!.items.push(m);}return out;},[messages]);
  if(!thread)return <div className="flex h-full flex-col items-center justify-center px-8 py-12 text-center"><span className="grid size-20 place-items-center rounded-3xl bg-neutral text-neutral-content"><FiMessageCircle aria-hidden size={34}/></span><p className="mt-6 text-[10px] font-semibold uppercase tracking-widest text-muted">A little conversation goes a long way</p><h2 className="mt-2 text-2xl font-semibold">Learning is better together.</h2><p className="mt-3 max-w-sm text-sm leading-6 text-muted">Choose a conversation to catch up, ask for help, or share what you’re learning.</p><img src="/illustrations/study-books.webp" alt="" width={160} height={120} className="mt-8 h-28 w-36 object-contain" /></div>;
  const others=dedupeParticipants(thread.participants).filter(p=>p.user.id!==myId),person=others[0]?.user;
  return <div className="flex h-full min-h-0 flex-col"><header className="flex shrink-0 items-center gap-3 border-b border-base-300 bg-base-100 px-4 py-4 sm:px-6">{onBack?<button aria-label="Back to conversations" onClick={onBack} className="btn btn-ghost btn-sm btn-circle lg:hidden"><FiArrowLeft aria-hidden/></button>:null}<span className={`grid size-11 shrink-0 place-items-center rounded-2xl text-xs font-semibold ${person?accentFor(person.firstName):'bg-base-200'}`}>{person?initials(person.firstName,person.lastName):'Me'}</span><div className="min-w-0 flex-1"><h2 className="truncate text-sm font-semibold">{threadTitle(thread,myId)}</h2><p className="mt-1 truncate text-xs text-muted">{others.length>1?`${others.length+1} people · Group conversation`:person?'Direct conversation':'Personal notes'}</p></div></header>
    {chatError?<p role="alert" className="mx-4 mt-3 rounded-xl bg-error text-error-content p-3 text-xs text-error">{chatError} Your message is still in the composer.</p>:null}
    {loading?<div className="min-h-0 flex-1"><LoadingBlock label="Loading messages…" /></div>:error?<div className="min-h-0 flex-1"><ErrorBlock message={error} onRetry={onRetry}/></div>:<ul ref={list} onScroll={()=>{const el=list.current;if(el)nearBottom.current=el.scrollHeight-el.scrollTop-el.clientHeight<90;}} className="min-h-0 flex-1 space-y-5 overflow-y-auto bg-base-200 px-4 py-6 sm:px-6">{!grouped.length?<li className="py-12 text-center"><FiMessageCircle aria-hidden size={28} className="mx-auto text-muted"/><p className="mt-3 text-sm font-semibold">Say hello.</p><p className="mt-2 text-xs text-muted">This is the beginning of your conversation.</p></li>:grouped.map(g=><li key={g.label}><div className="mb-5 flex justify-center"><span className="rounded-full bg-base-100 px-3 py-1 text-[10px] text-muted">{g.label}</span></div>{g.items.map(m=>{const mine=m.senderId===myId;return <div key={m.id} className={`chat ${mine?'chat-end':'chat-start'}`}><div className="chat-header mb-1 text-[10px] text-muted">{mine?'You':`${m.sender.firstName} ${m.sender.lastName}`}<time className="ml-2" dateTime={m.createdAt}>{format(parseISO(m.createdAt),'HH:mm')}</time></div><div className={`chat-bubble max-w-[90%] whitespace-pre-wrap break-words text-sm leading-6 [overflow-wrap:anywhere] sm:max-w-[80%] ${mine?'chat-bubble-neutral':'bg-base-100 text-base-content'}`}>{m.body}</div></div>;})}</li>)}</ul>}
    <MessageComposer draft={draft} onDraft={onDraft} onSend={onSend} sending={sending||loading||!!error}/>
  </div>;
}
