import { FiPlus,FiX } from 'react-icons/fi';
import type { ChangePractice,PracticeDraft } from './practice-draft';

export function PracticeQuestionFields({ draft, change }: { draft: PracticeDraft; change: ChangePractice }) {
  if (draft.type === 'MATCHING') return <div className="space-y-3"><p className="text-sm font-medium">Matching pairs</p>{draft.pairs.map((pair, index) => <div key={index} className="flex items-center gap-2"><input required aria-label={`Pair ${index + 1} word`} className="input min-w-0 flex-1" placeholder="Word" value={pair.left} onChange={event => change('pairs', draft.pairs.map((p,i) => i === index ? {...p,left:event.target.value} : p))}/><span className="text-muted">↔</span><input required aria-label={`Pair ${index + 1} match`} className="input min-w-0 flex-1" placeholder="Meaning" value={pair.right} onChange={event => change('pairs', draft.pairs.map((p,i) => i === index ? {...p,right:event.target.value} : p))}/><button type="button" className="btn btn-sm btn-square btn-ghost" aria-label={`Remove pair ${index+1}`} disabled={draft.pairs.length < 2} onClick={() => change('pairs',draft.pairs.filter((_,i)=>i!==index))}><FiX aria-hidden/></button></div>)}<button type="button" className="btn btn-sm btn-ghost" onClick={() => change('pairs',[...draft.pairs,{left:'',right:''}])}><FiPlus aria-hidden/>Add pair</button></div>;
  if (draft.type === 'FILL_BLANK') return <div className="space-y-4"><p className="text-xs text-muted">Use ___ where students should fill in the missing word.</p>{draft.sentences.map((sentence,index) => <div key={index} className="space-y-3 rounded-box bg-base-200 p-4"><label className="block text-xs font-medium">Sentence {index+1}<input required className="input mt-2 w-full border-0" value={sentence.text} placeholder="Ich ___ Deutsch." onChange={event=>change('sentences',draft.sentences.map((row,i)=>i===index?{...row,text:event.target.value}:row))}/></label><div className="flex items-end gap-2"><label className="grow text-xs font-medium">Answer<input required className="input mt-2 w-full border-0" value={sentence.answer} onChange={event=>change('sentences',draft.sentences.map((row,i)=>i===index?{...row,answer:event.target.value}:row))}/></label><button type="button" className="btn btn-square btn-ghost" aria-label={`Remove sentence ${index+1}`} disabled={draft.sentences.length<2} onClick={()=>change('sentences',draft.sentences.filter((_,i)=>i!==index))}><FiX aria-hidden/></button></div></div>)}<button type="button" className="btn btn-sm btn-ghost" onClick={()=>change('sentences',[...draft.sentences,{text:'',answer:''}])}><FiPlus aria-hidden/>Add sentence</button></div>;
  return <div className="space-y-4">
    <label className="block text-sm font-medium">{draft.type==='TRUE_FALSE'?'Statement':draft.type==='MCQ'?'Question':'Task'}<textarea required className="textarea mt-2 w-full" rows={3} value={draft.prompt} onChange={event=>change('prompt',event.target.value)} placeholder="What would you like the student to do?"/></label>
    {draft.type==='MCQ'?<fieldset className="space-y-2"><legend className="mb-3 text-sm font-medium">Answers <span className="font-normal text-muted">· select the correct one</span></legend>{draft.options.map((option,index)=><label key={index} className={`flex items-center gap-3 rounded-field p-2 ${draft.correctIndex===index?'bg-success text-success-content':'bg-base-200'}`}><input type="radio" className="radio radio-sm" name="studio-correct-answer" aria-label={`Answer ${index+1} is correct`} checked={draft.correctIndex===index} onChange={()=>change('correctIndex',index)}/><input required className="input min-w-0 grow border-0 bg-transparent" aria-label={`Answer ${index+1}`} placeholder={`Answer ${index+1}`} value={option} onChange={event=>change('options',draft.options.map((value,i)=>i===index?event.target.value:value))}/></label>)}</fieldset>:null}
    {draft.type==='TRUE_FALSE'?<fieldset><legend className="mb-2 text-sm font-medium">Correct answer</legend><div className="grid grid-cols-2 gap-3">{[true,false].map(value=><button key={String(value)} type="button" className={`btn ${draft.correct===value?'btn-neutral':'border-0 bg-base-200'}`} aria-pressed={draft.correct===value} onClick={()=>change('correct',value)}>{value?'True':'False'}</button>)}</div></fieldset>:null}
    {draft.type==='WRITING'?<label className="block text-sm font-medium">Minimum words <span className="font-normal text-muted">optional</span><input type="number" min={0} className="input mt-2 w-full" value={draft.minWords} onChange={event=>change('minWords',event.target.value)}/></label>:null}
    {draft.type==='DOCUMENT'?<label className="block text-sm font-medium">Allowed file types<input className="input mt-2 w-full" value={draft.allowedTypes} onChange={event=>change('allowedTypes',event.target.value)}/></label>:null}
  </div>;
}
