import { FiArrowUpRight,FiCheckCircle,FiClock } from 'react-icons/fi';
import { Link } from 'react-router-dom';
import type { TeachingOverview } from './dashboard-data';
export function TeachingActionRail({ data:d }: {data:TeachingOverview}){
  const actions=[...d.attendanceNeeds.slice(0,3).map(a=>({id:a.id,title:'Mark attendance',hint:`${a.className} · ${a.unmarked} unmarked`,to:`/teacher/attendance?session=${a.id}`})),...d.gradingByClass.filter(g=>g.assessments>0).slice(0,3).map(g=>({id:g.classGroupId,title:`Review ${g.assessments} assessment${g.assessments===1?'':'s'}`,hint:g.className,to:`/teacher/grading?classGroupId=${g.classGroupId}&status=SUBMITTED`}))];
  if(d.pendingHomeworkCount)actions.push({id:'homework',title:`Review ${d.pendingHomeworkCount} homework task${d.pendingHomeworkCount===1?'':'s'}`,hint:'Homework',to:'/teacher/assignments'});
  if(d.pendingActivityCount)actions.push({id:'activities',title:`Review ${d.pendingActivityCount} activities`,hint:'Class exercises',to:'/teacher/grading?view=activities'});
  return <aside className="space-y-5"><section className="card bg-base-100 p-5"><div className="flex items-center justify-between"><h2 className="text-base font-semibold">Needs attention</h2><FiCheckCircle aria-hidden className="text-base-content/45"/></div>{actions.length?<ul className="mt-4 space-y-2">{actions.map(a=><li key={a.id}><Link to={a.to} className="flex items-center justify-between gap-3 rounded-2xl bg-base-200/60 p-4 hover:bg-base-200"><div className="min-w-0"><p className="text-xs font-semibold">{a.title}</p><p className="mt-1 text-[10px] leading-4 text-base-content/55">{a.hint}</p></div><FiArrowUpRight aria-hidden className="shrink-0"/></Link></li>)}</ul>:<div className="mt-5 rounded-2xl bg-base-200 p-5"><p className="text-sm font-semibold">All caught up.</p><Link to="/teacher/content" className="btn btn-sm mt-4">Prepare a lesson</Link></div>}</section><section className="card bg-base-100 p-5"><div className="flex items-center justify-between"><h2 className="text-base font-semibold">Coming up</h2><Link to="/teacher/schedule" className="text-xs underline underline-offset-4">View calendar</Link></div>{d.upcoming.length?<ul className="mt-4 space-y-3">{d.upcoming.slice(0,3).map(s=><li key={s.id}><Link to={`/teacher/schedule?session=${s.id}`} className="block rounded-2xl p-4 hover:bg-base-200"><p className="flex items-center gap-2 text-[10px] text-base-content/55"><FiClock aria-hidden/>{new Date(s.startAt).toLocaleDateString('en-GB',{day:'numeric',month:'short'})} · {new Date(s.startAt).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'})}</p><p className="mt-2 text-sm font-semibold">{s.title||s.classGroup.name}</p></Link></li>)}</ul>:<p className="mt-5 rounded-2xl bg-base-200 p-4 text-xs leading-5 text-base-content/55">No upcoming classes.</p>}</section></aside>;
}
