import { FiCheckSquare } from 'react-icons/fi';
import { STATUS_META } from '../../components/attendance/constants';
import { EmptyBlock,ErrorBlock,LoadingBlock } from '../../components/common/PageState';
import { useApi } from '../../hooks/useApi';
import { getMyAttendance } from '../../lib/services';
export function StudentAttendance(){
  const attendance=useApi('my-attendance',getMyAttendance);
  const s=attendance.data?.summary;
  return <div className="space-y-5"><section className="card border border-base-300 bg-base-100 p-6 sm:p-8"><span className="mb-4 grid size-11 place-items-center rounded-2xl bg-neutral text-neutral-content"><FiCheckSquare aria-hidden size={21}/></span><p className="text-xs uppercase tracking-widest text-base-content/50">Class records</p><h1 className="mt-2 text-3xl font-semibold">Your attendance</h1><p className="mt-3 max-w-xl text-sm leading-6 text-base-content/60">Your attendance and teacher notes. Ask your teacher for corrections.</p></section>{attendance.loading?<LoadingBlock label="Loading attendance…"/>:attendance.error?<ErrorBlock message={attendance.error} onRetry={attendance.refetch}/>:<><div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[{label:'Attendance rate',value:s?.total?`${s.percentage}%`:'—'},{label:'Present or late',value:(s?.present??0)+(s?.late??0)},{label:'Absent',value:s?.absent??0},{label:'Excused',value:s?.excused??0}].map(stat=><section key={stat.label} className="card border border-base-300 bg-base-100 p-5"><p className="text-xs text-base-content/60">{stat.label}</p><p className="mt-2 text-3xl font-semibold">{stat.value}</p></section>)}</div><p className="text-xs text-base-content/55">Rate = present + late / marked sessions. Cancelled and unmarked sessions are excluded.</p><section className="card overflow-hidden border border-base-300 bg-base-100"><h2 className="border-b border-base-300 p-5 text-sm font-semibold">Your class history</h2>{!attendance.data?.history.length?<div className="p-8"><EmptyBlock title="No attendance records yet" hint="Your teacher will record attendance when your classes start."/></div>:attendance.data.history.map(r=>{const status=STATUS_META[r.status as keyof typeof STATUS_META];return <article key={r.id} className="flex flex-wrap items-start justify-between gap-3 border-b border-base-300 p-5 last:border-0"><div><h3 className="text-sm font-semibold">{r.session.title||'Class session'}</h3><p className="mt-1 text-xs text-base-content/55">{new Date(r.session.startAt).toLocaleString('en-GB')}</p>{r.note?<p className="mt-3 max-w-xl whitespace-pre-wrap break-words rounded-xl bg-base-200 p-3 text-xs leading-5">{r.note}</p>:null}</div><span className={`rounded-full border px-3 py-1 text-xs ${status?.chip??'bg-base-200'}`}>{status?.label??r.status}</span></article>;})}</section></>}</div>;
}
