import assert from 'node:assert/strict';
import request from 'supertest';
import { createApp } from '../../app.js';
import { prisma } from '../../lib/prisma.js';
const dataOf=<T>(r:{body:unknown}):T=>(r.body as {data:T}).data;
const app=createApp(),stamp=`attendance-test-${Date.now()}`;
const users:string[]=[],groups:string[]=[];
async function login(email:string,password:string){const r=await request(app).post('/api/auth/login').send({email,password});assert.equal(r.status,200);return dataOf<{tokens:{accessToken:string}}>(r).tokens.accessToken;}
const call=(token:string)=>({get:(path:string)=>request(app).get(`/api${path}`).auth(token,{type:'bearer'}),post:(path:string,body:object)=>request(app).post(`/api${path}`).auth(token,{type:'bearer'}).send(body),put:(path:string,body:object)=>request(app).put(`/api${path}`).auth(token,{type:'bearer'}).send(body),patch:(path:string,body:object)=>request(app).patch(`/api${path}`).auth(token,{type:'bearer'}).send(body)});
try{
  const academic=call(await login('academic@sparch.rw','Academic123!')),finance=call(await login('finance@sparch.rw','Finance123!'));
  const base=await prisma.classGroup.findFirstOrThrow(),seedTeacher=await prisma.user.findUniqueOrThrow({where:{email:'clarisse@sparch.rw'}}),seedStudent=await prisma.user.findUniqueOrThrow({where:{email:'nella@student.sparch.rw'}});
  const makeUser=async(role:'TEACHER'|'STUDENT',suffix:string)=>{const u=await prisma.user.create({data:{email:`${stamp}-${suffix}@test.local`,firstName:'Test',lastName:suffix,role,status:'ACTIVE',passwordHash:role==='TEACHER'?seedTeacher.passwordHash:seedStudent.passwordHash}});users.push(u.id);return u;};
  const owner=await makeUser('TEACHER','owner'),outsider=await makeUser('TEACHER','outsider'),u=await makeUser('STUDENT','student');
  const student=await prisma.student.create({data:{userId:u.id,studentCode:stamp,campusId:base.campusId,status:'ACTIVE',intendedLevelId:base.levelId,currentLevelId:base.levelId}});
  const teacher=call(await login(owner.email,'Teacher123!')),other=call(await login(outsider.email,'Teacher123!')),self=call(await login(u.email,'Student123!'));
  assert.equal((await teacher.put(`/users/${owner.id}/teaching-levels`,{levelIds:[base.levelId]})).status,403);
  assert.equal((await finance.put(`/users/${owner.id}/teaching-levels`,{levelIds:[base.levelId]})).status,403);
  assert.equal((await academic.put(`/users/${u.id}/teaching-levels`,{levelIds:[base.levelId]})).status,404);
  assert.equal((await academic.put(`/users/${owner.id}/teaching-levels`,{levelIds:['unknown']})).status,400);
  assert.equal((await teacher.post(`/content/levels/${base.levelId}/modules`,{title:'Forbidden',order:100})).status,403);
  assert.equal((await academic.put(`/users/${owner.id}/teaching-levels`,{levelIds:[base.levelId]})).status,200);
  assert.deepEqual(dataOf<string[]>(await teacher.get('/users/me/teaching-levels')),[base.levelId]);
  const group=await prisma.classGroup.create({data:{code:stamp,name:stamp,levelId:base.levelId,intakeId:base.intakeId,campusId:base.campusId}});groups.push(group.id);
  assert.equal((await teacher.patch(`/classes/${group.id}`,{teacherId:owner.id})).status,403);
  assert.equal((await academic.patch(`/classes/${group.id}`,{teacherId:outsider.id})).status,403);
  assert.equal((await academic.patch(`/classes/${group.id}`,{teacherId:owner.id})).status,200);
  assert.equal((await other.get(`/classes/${group.id}`)).status,403);
  assert.equal((await academic.put(`/users/${owner.id}/teaching-levels`,{levelIds:[]})).status,409);
  await prisma.enrollment.create({data:{studentId:student.id,levelId:base.levelId,intakeId:base.intakeId,campusId:base.campusId,classGroupId:group.id,status:'ACTIVE',enrolledAt:new Date(Date.now()-10*86400000),totalFee:0,currency:'RWF'}});
  const makeSession=(suffix:string,status:'SCHEDULED'|'COMPLETED'|'CANCELLED',offset:number)=>prisma.classSession.create({data:{classGroupId:group.id,teacherId:owner.id,title:`${stamp}-${suffix}`,mode:'ONSITE',status,startAt:new Date(Date.now()+offset),endAt:new Date(Date.now()+offset+3600000)}});
  const past=await makeSession('past','COMPLETED',-86400000),future=await makeSession('future','SCHEDULED',86400000),cancelled=await makeSession('cancelled','CANCELLED',-2*86400000);
  const route=(id:string)=>`/sessions/${id}/attendance`,present={records:[{studentId:student.id,status:'PRESENT',note:'Arrived on time'}]};
  assert.equal((await teacher.post(route(future.id),present)).status,409);
  assert.equal((await teacher.post(route(cancelled.id),present)).status,409);
  assert.equal((await other.post(route(past.id),present)).status,403);
  assert.equal((await self.post(route(past.id),present)).status,403);
  assert.equal((await finance.post(route(past.id),present)).status,403);
  assert.equal((await teacher.post(route(past.id),{records:[...present.records,...present.records]})).status,400);
  assert.equal((await teacher.post(route(past.id),{records:[...present.records,{studentId:'foreign',status:'ABSENT'}]})).status,400);
  assert.equal(await prisma.attendance.count({where:{sessionId:past.id}}),0);
  assert.equal((await teacher.post(route(past.id),present)).status,200);
  const record=await prisma.attendance.findUniqueOrThrow({where:{sessionId_studentId:{sessionId:past.id,studentId:student.id}}});
  assert.equal((await teacher.post(route(past.id),{records:[{studentId:student.id,status:'ABSENT',expectedUpdatedAt:null}]})).status,409);
  assert.equal((await other.patch(`/sessions/attendance/${record.id}`,{status:'ABSENT'})).status,403);
  assert.equal((await academic.patch(`/sessions/attendance/${record.id}`,{status:'LATE',note:'Arrived 10 minutes late'})).status,200);
  assert.equal((await teacher.post(route(past.id),{records:[{studentId:student.id,status:'LATE'}]})).status,200);
  assert.equal((await prisma.attendance.findUniqueOrThrow({where:{id:record.id}})).note,'Arrived 10 minutes late');
  assert.equal((await teacher.patch(`/sessions/attendance/${record.id}`,{note:null})).status,200);
  assert.equal((await prisma.attendance.findUniqueOrThrow({where:{id:record.id}})).note,null);
  assert.equal((await teacher.post(route(past.id),{records:[{studentId:student.id,status:'ABSENT',expectedUpdatedAt:record.updatedAt.toISOString()}]})).status,409);
  const history=await self.get('/attendance/me');assert.equal(history.status,200);assert.equal(dataOf<{summary:{late:number;percentage:number}}>(history).summary.late,1);assert.equal(dataOf<{summary:{late:number;percentage:number}}>(history).summary.percentage,100);
  assert.equal(dataOf<{attendanceNeeds:unknown[]}>(await teacher.get('/dashboards/teacher')).attendanceNeeds.length,0);
  assert.equal(dataOf<{late:number}[]>(await teacher.get(`/attendance/summary?classGroupId=${group.id}`))[0].late,1);
  assert.equal((await teacher.get(`/attendance/export?classGroupId=${group.id}`)).status,200);
  assert.equal((await teacher.post(route(past.id),{records:[{studentId:student.id,status:'ABSENT'}]})).status,200);
  assert.equal((await teacher.post(route(past.id),{records:[{studentId:student.id,status:'EXCUSED'}]})).status,200);
  assert.equal(await prisma.notification.count({where:{userId:u.id,title:'Low attendance'}}),1);
  const lateJoiner=await makeUser('STUDENT','latejoiner');const profile=await prisma.student.create({data:{userId:lateJoiner.id,studentCode:`${stamp}-late`,campusId:base.campusId,status:'ACTIVE',intendedLevelId:base.levelId}});
  await prisma.enrollment.create({data:{studentId:profile.id,levelId:base.levelId,intakeId:base.intakeId,campusId:base.campusId,classGroupId:group.id,status:'ACTIVE',totalFee:0,currency:'RWF'}});
  assert.equal((await teacher.post(route(past.id),{records:[{studentId:profile.id,status:'ABSENT'}]})).status,400);
  assert.equal(dataOf<unknown[]>(await teacher.get(`/sessions/${past.id}/roster`)).length,1);
  assert.equal((await academic.patch(`/classes/${group.id}`,{teacherId:null})).status,200);
  assert.equal((await teacher.get(`/sessions/${past.id}/roster`)).status,403);
  assert.equal((await academic.put(`/users/${owner.id}/teaching-levels`,{levelIds:[]})).status,200);
  assert.equal((await teacher.get(`/content/levels/${base.levelId}/modules`)).status,403);
  process.stdout.write('Attendance and teaching integration passed: role boundaries, assignments/revocation, atomic marking, corrections, history, exports and alerts.\n');
}finally{
  const sessionIds=(await prisma.classSession.findMany({where:{classGroupId:{in:groups}},select:{id:true}})).map(s=>s.id);
  await prisma.auditLog.deleteMany({where:{OR:[{entityId:{in:[...users,...groups,...sessionIds]}},{actorId:{in:users}}]}});
  await prisma.activityEvent.deleteMany({where:{OR:[{classGroupId:{in:groups}},{actorId:{in:users}}]}});
  await prisma.classGroup.deleteMany({where:{id:{in:groups}}});
  await prisma.user.deleteMany({where:{id:{in:users}}});await prisma.$disconnect();
}
