// NODE_ENV=test LOG_LEVEL=silent UNPAID_ACCESS=NONE node --import tsx src/modules/sessions/schedule-workflow.integration.ts
import assert from 'node:assert/strict';
import request from 'supertest';
import { createApp } from '../../app.js';
import { recalculateStudentFinance } from '../../lib/finance.js';
import { prisma } from '../../lib/prisma.js';
import { createPayment } from '../payments/payments.service.js';
const app=createApp(),stamp=`schedule-test-${Date.now()}`;
const users:string[]=[],groups:string[]=[],sessionIds:string[]=[],extraAuditIds:string[]=[];
let learnerId:string|undefined;
async function auth(email:string,password:string) {const r=await request(app).post('/api/auth/login').send({email,password});assert.equal(r.status,200);return String((r.body as {data:{tokens:{accessToken:string}}}).data.tokens.accessToken);}
function api(token:string) {return {get:(p:string)=>request(app).get(`/api${p}`).set('Authorization',`Bearer ${token}`),post:(p:string,body:object)=>request(app).post(`/api${p}`).set('Authorization',`Bearer ${token}`).send(body),patch:(p:string,body:object)=>request(app).patch(`/api${p}`).set('Authorization',`Bearer ${token}`).send(body)};}
type Row={id:string;status:string;meetingUrl:string|null;recordingUrl:string|null;materials?:unknown[];accessMessage?:string|null};
try {
  const owner=await prisma.user.findUniqueOrThrow({where:{email:'clarisse@sparch.rw'}});
  const base=await prisma.classGroup.findFirstOrThrow({where:{teacherId:owner.id}});
  const other=await prisma.user.create({data:{email:`${stamp}-teacher@test.local`,firstName:'Other',lastName:'Teacher',role:'TEACHER',status:'ACTIVE',passwordHash:owner.passwordHash}});users.push(other.id);
  await prisma.teacherLevel.create({data:{teacherId:other.id,levelId:base.levelId}});
  const seededStudent=await prisma.user.findUniqueOrThrow({where:{email:'nella@student.sparch.rw'}});
  const u=await prisma.user.create({data:{email:`${stamp}-student@test.local`,firstName:'Test',lastName:'Learner',role:'STUDENT',status:'ACTIVE',passwordHash:seededStudent.passwordHash}});users.push(u.id);
  const learner=await prisma.student.create({data:{userId:u.id,studentCode:stamp,campusId:base.campusId,currentLevelId:base.levelId,status:'ACTIVE'}});learnerId=learner.id;
  const makeGroup=async(suffix:string,teacherId:string)=>{const g=await prisma.classGroup.create({data:{code:`${stamp}-${suffix}`,name:stamp,teacherId,levelId:base.levelId,intakeId:base.intakeId,campusId:base.campusId}});groups.push(g.id);return g;};
  const own=await makeGroup('own',owner.id),foreign=await makeGroup('foreign',other.id);
  await prisma.enrollment.create({data:{studentId:learner.id,classGroupId:own.id,levelId:base.levelId,intakeId:base.intakeId,campusId:base.campusId,totalFee:100}});
  await prisma.charge.create({data:{studentId:learner.id,type:'TUITION',description:stamp,amount:100,currency:'RWF'}});
  await recalculateStudentFinance(prisma,learner.id);
  const teacher=api(await auth(owner.email,'Teacher123!')),outsider=api(await auth(other.email,'Teacher123!')),student=api(await auth(u.email,'Student123!')),finance=api(await auth('finance@sparch.rw','Finance123!')),admin=api(await auth('admin@sparch.rw','Admin123!'));
  const future=new Date(Date.now()+400*86400000);future.setUTCHours(9,0,0,0);
  const input={classGroupId:own.id,title:stamp,mode:'ONLINE',provider:'GOOGLE_MEET',meetingUrl:'https://meet.google.com/test',startAt:future.toISOString(),endAt:new Date(future.getTime()+3600000).toISOString(),timezone:'Africa/Kigali'};
  await request(app).get('/api/sessions').expect(401);
  for(const path of ['/sessions','/attendance/summary','/attendance/export'])await finance.get(path).expect(403);
  await student.post('/sessions',input).expect(403);
  await outsider.post('/sessions',input).expect(403);
  await teacher.post('/sessions',{...input,meetingUrl:'javascript:alert(1)'}).expect(400);
  await teacher.post('/sessions',{...input,timezone:'Bad/Timezone'}).expect(400);
  await admin.post('/sessions',{...input,teacherId:u.id}).expect(403);
  let r=await teacher.post('/sessions',input).expect(201);const id=String((r.body as {data:Row}).data.id);sessionIds.push(id);
  await teacher.post('/sessions',input).expect(409);
  const secondOwn=await makeGroup('second-own',owner.id);
  await teacher.post('/sessions',{...input,classGroupId:secondOwn.id}).expect(409);
  const roomDate=new Date(future.getTime()+3*86400000);
  const roomBody={...input,classGroupId:foreign.id,mode:'ONSITE',room:stamp,startAt:roomDate.toISOString(),endAt:new Date(roomDate.getTime()+3600000).toISOString()};
  const roomResult=await admin.post('/sessions',roomBody).expect(201);sessionIds.push(String((roomResult.body as {data:Row}).data.id));
  await teacher.post('/sessions',{...roomBody,classGroupId:own.id}).expect(409);
  const academic=api(await auth('academic@sparch.rw','Academic123!'));
  await academic.get(`/sessions/${id}`).expect(200);
  await finance.get(`/sessions/${id}/roster`).expect(403);
  await outsider.patch(`/sessions/${id}`,{notes:'Unauthorized'}).expect(403);
  await outsider.post(`/sessions/${id}/cancel`,{}).expect(403);
  await outsider.post(`/sessions/${id}/materials`,{title:'Unauthorized',type:'NOTE'}).expect(403);
  await outsider.post(`/sessions/${id}/attendance`,{records:[{studentId:learner.id,status:'PRESENT'}]}).expect(403);
  await outsider.get(`/sessions/${id}`).expect(403);await outsider.get(`/sessions/${id}/roster`).expect(403);
  await outsider.get(`/attendance/summary?classGroupId=${own.id}`).expect(403);await outsider.get(`/attendance/export?classGroupId=${own.id}`).expect(403);
  r=await outsider.get('/sessions');assert.ok(!(r.body as {data:Row[]}).data.some(x=>x.id===id));
  r=await student.get(`/sessions/me/${id}`).expect(200);assert.equal((r.body as {data:Row}).data.meetingUrl,null);assert.ok((r.body as {data:Row}).data.accessMessage);
  const financeActor=await prisma.user.findUniqueOrThrow({where:{email:'finance@sparch.rw'}}),method=await prisma.paymentMethodConfig.findFirstOrThrow({where:{isActive:true}});
  await createPayment({studentId:learner.id,methodId:method.id,amount:100,reference:stamp,notes:'Temporary integration fixture',paidAt:undefined,currency:'RWF'},financeActor.id);
  r=await student.get(`/sessions/me/${id}`).expect(200);assert.equal((r.body as {data:Row}).data.meetingUrl,input.meetingUrl);
  await teacher.patch(`/sessions/${id}`,{status:'LIVE'}).expect(400);await teacher.patch(`/sessions/${id}`,{status:'COMPLETED'}).expect(400);
  const materialResponse=await teacher.post(`/sessions/${id}/materials`,{title:'Notes',type:'NOTE',description:'Five German phrases.'}).expect(201);
  const materialId=String((materialResponse.body as {data:Row}).data.id);extraAuditIds.push(materialId);
  await request(app).delete(`/api/sessions/materials/${materialId}`).set('Authorization',`Bearer ${await auth(other.email,'Teacher123!')}`).expect(403);
  r=await student.get(`/sessions/me/${id}`);assert.equal((r.body as {data:Row}).data.materials?.length,1);
  await request(app).delete(`/api/sessions/materials/${materialId}`).set('Authorization',`Bearer ${await auth(owner.email,'Teacher123!')}`).expect(200);
  r=await student.get(`/sessions/me/${id}`);assert.equal((r.body as {data:Row}).data.materials?.length,0);
  const moved=new Date(future.getTime()+86400000),movedEnd=new Date(moved.getTime()+3600000);
  await teacher.patch(`/sessions/${id}`,{startAt:moved.toISOString(),endAt:movedEnd.toISOString()}).expect(200);
  assert.equal((await prisma.classSession.findUniqueOrThrow({where:{id}})).status,'RESCHEDULED');
  assert.ok(await prisma.notification.findFirst({where:{userId:u.id,title:'Class rescheduled',data:{path:['sessionId'],equals:id}}}));
  const movedAgain=new Date(future.getTime()+2*86400000);
  await teacher.post(`/sessions/${id}/reschedule`,{startAt:movedAgain.toISOString(),endAt:new Date(movedAgain.getTime()+3600000).toISOString(),reason:'Teacher availability'}).expect(200);
  assert.ok(await prisma.auditLog.findFirst({where:{entityId:id,action:'SESSION_RESCHEDULED',reason:'Teacher availability'}}));
  const blockDate=new Date(future.getTime()+7*86400000);
  const blocker=await prisma.classSession.create({data:{classGroupId:own.id,teacherId:owner.id,title:stamp,startAt:blockDate,endAt:new Date(blockDate.getTime()+3600000)}});sessionIds.push(blocker.id);
  const count=await prisma.classSession.count({where:{classGroupId:own.id}});
  await teacher.post('/sessions',{...input,repeatWeeks:2}).expect(409);
  assert.equal(await prisma.classSession.count({where:{classGroupId:own.id}}),count,'Series must roll back completely');
  await teacher.post(`/sessions/${id}/cancel`,{reason:'Fixture cancellation'}).expect(200);
  await teacher.patch(`/sessions/${id}`,{startAt:future.toISOString()}).expect(409);
  r=await student.get(`/sessions/me/${id}`);assert.equal((r.body as {data:Row}).data.meetingUrl,null);
  const current=await prisma.classSession.create({data:{classGroupId:own.id,teacherId:owner.id,title:stamp,startAt:new Date(Date.now()-60000),endAt:new Date(Date.now()+600000),meetingUrl:input.meetingUrl}});sessionIds.push(current.id);
  await teacher.patch(`/sessions/${current.id}`,{status:'LIVE'}).expect(200);
  await teacher.patch(`/sessions/${current.id}`,{status:'COMPLETED'}).expect(200);
  await teacher.post(`/sessions/${current.id}/cancel`,{}).expect(409);
  await teacher.patch(`/sessions/${current.id}`,{recordingUrl:'https://example.com/recording',notes:'Review'}).expect(200);
  r=await student.get(`/sessions/me/${current.id}`);assert.equal((r.body as {data:Row}).data.meetingUrl,null);assert.equal((r.body as {data:Row}).data.recordingUrl,'https://example.com/recording');
  const foreignSession=await prisma.classSession.create({data:{classGroupId:foreign.id,teacherId:other.id,title:stamp,startAt:future,endAt:new Date(future.getTime()+3600000)}});sessionIds.push(foreignSession.id);
  await student.get(`/sessions/me/${foreignSession.id}`).expect(403);
  await prisma.attendance.createMany({data:[{sessionId:current.id,studentId:learner.id,status:'PRESENT'},{sessionId:foreignSession.id,studentId:learner.id,status:'ABSENT'}]});
  r=await teacher.get(`/attendance/summary?studentId=${learner.id}`).expect(200);const summary=(r.body as {data:{present:number;absent:number}[]}).data;assert.equal(summary[0]?.present,1);assert.equal(summary[0]?.absent,0);
  await prisma.student.update({where:{id:learner.id},data:{status:'SUSPENDED'}});
  await student.get('/sessions/me?scope=all').expect(403);await student.get(`/sessions/me/${id}`).expect(403);await student.get('/attendance/me').expect(403);
  await prisma.student.update({where:{id:learner.id},data:{status:'ACTIVE'}});
  r=await teacher.post('/sessions',{...input,startAt:new Date(future.getTime()+30*86400000).toISOString(),endAt:new Date(future.getTime()+30*86400000+3600000).toISOString(),repeatWeeks:3}).expect(201);
  const rows=await prisma.classSession.findMany({where:{classGroupId:own.id,title:stamp}});sessionIds.push(...rows.map(x=>x.id));
  assert.equal(rows.length,6,'Three repeated classes committed together');
  for(let race=0;race<5;race++) {
    const raceDate=new Date(future.getTime()+(100+race)*86400000);
    const raceBody={...input,startAt:raceDate.toISOString(),endAt:new Date(raceDate.getTime()+3600000).toISOString()};
    const racers=await Promise.all([teacher.post('/sessions',raceBody),teacher.post('/sessions',raceBody)]);
    const raceRows=await prisma.classSession.findMany({where:{classGroupId:own.id,startAt:raceDate}});sessionIds.push(...raceRows.map(r=>r.id));
    assert.deepEqual(racers.map(r=>r.status).sort(),[201,409],'Concurrent overlapping writes must not both commit');
  }
  process.stdout.write('Schedule integration passed: role scopes, payment/account access, materials, lifecycle, rescheduling notifications, overlaps and atomic repetition.\n');
}finally{
  const remaining=await prisma.classSession.findMany({where:{classGroupId:{in:groups}},select:{id:true}});
  const ids=[...new Set([...sessionIds,...remaining.map(r=>r.id)])];
  await prisma.notification.deleteMany({where:{OR:[{userId:{in:users}},...ids.map(id=>({data:{path:['sessionId'],equals:id}}))]}});
  const materials=await prisma.sessionMaterial.findMany({where:{sessionId:{in:ids}},select:{id:true}});
  const payments=learnerId?await prisma.payment.findMany({where:{studentId:learnerId},select:{id:true}}):[];
  await prisma.auditLog.deleteMany({where:{OR:[{entityId:{in:[...ids,...extraAuditIds,...materials.map(m=>m.id),...payments.map(p=>p.id)]}},{actorId:{in:users}}]}});
  await prisma.classGroup.deleteMany({where:{id:{in:groups}}});
  if(learnerId){await prisma.receipt.deleteMany({where:{payment:{studentId:learnerId}}});await prisma.payment.deleteMany({where:{studentId:learnerId}});await prisma.charge.deleteMany({where:{studentId:learnerId}});await prisma.studentFinance.deleteMany({where:{studentId:learnerId}});await prisma.activityEvent.deleteMany({where:{studentId:learnerId}});}
  await prisma.refreshToken.deleteMany({where:{userId:{in:users}}});await prisma.user.deleteMany({where:{id:{in:users}}});await prisma.$disconnect();
}
