import { useState } from 'react';
import { FiCalendar } from 'react-icons/fi';
import type { SessionItem } from '../../lib/services';
import { sessionStatusLabel } from '../../lib/sessions-ui';
export function AttendanceSessionList({ sessions,id,onPick,disabled }: { sessions:SessionItem[];id:string|null;onPick:(id:string)=>void;disabled:boolean }) {
  const [classId,setClassId]=useState('');
  const groups=[...new Map(sessions.filter(s=>s.classGroup).map(s=>[s.classGroup!.id,s.classGroup!.name])).entries()];
  const filtered=[...sessions].filter(s=>!classId||s.classGroup?.id===classId).sort((a,b)=>Date.parse(b.startAt)-Date.parse(a.startAt));
  return <section className="card min-w-0 border border-base-300 bg-base-100 p-4"><h2 className="flex items-center gap-2 text-sm font-semibold"><FiCalendar aria-hidden/>Class sessions</h2><label className="mt-4 block text-xs text-muted">Class<select aria-label="Filter attendance by class" value={classId} onChange={e=>setClassId(e.target.value)} className="select select-sm mt-1 w-full"><option value="">All your classes</option>{groups.map(([value,name])=><option key={value} value={value}>{name}</option>)}</select></label><ul className="mt-4 max-h-[65vh] space-y-2 overflow-y-auto">{filtered.map(s=>{const future=Date.parse(s.startAt)>Date.now(),cancelled=s.status==='CANCELLED';return <li key={s.id}><button disabled={disabled} aria-current={id===s.id?'true':undefined} onClick={()=>onPick(s.id)} className={`w-full rounded-2xl p-4 text-left ${id===s.id?'bg-neutral text-neutral-content':'bg-base-200 hover:bg-base-200'} ${future||cancelled?'opacity-60':''}`}><p className="text-xs opacity-65">{new Date(s.startAt).toLocaleDateString('en-GB',{day:'numeric',month:'short'})} · {new Date(s.startAt).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'})}</p><h3 className="mt-1 text-sm font-semibold">{s.title||s.classGroup?.name||'Class session'}</h3><p className="mt-3 text-[10px] font-semibold">{cancelled?'Cancelled':future?'Upcoming':sessionStatusLabel(s.status)}</p></button></li>;})}</ul>{!filtered.length?<p className="py-8 text-center text-xs text-muted">No sessions for this class.</p>:null}</section>;
}
