import { useState } from 'react';
import { FiDownload,FiSave } from 'react-icons/fi';
import { apiErrorMessage,downloadFile } from '../../lib/api';
import type { SessionItem,SessionRosterRow } from '../../lib/services';
import { AttendanceRow } from './AttendanceRow';
import { BulkBar } from './BulkBar';
import { StatsStrip } from './StatsStrip';
import { rosterStats } from './utils';
type Props={session:SessionItem;rows:SessionRosterRow[];draft:Record<string,{status:string;note:string|null}>;editable:boolean;saving:boolean;error:string|null;saved:boolean;change:(id:string,status:string,note?:string|null)=>void;discard:()=>void;save:()=>Promise<void>};
export function AttendanceRegister({session,rows,draft,editable,saving,error,saved,change,discard,save}:Props){
  const [q,setQ]=useState(''),[exportError,setExportError]=useState<string|null>(null),[exporting,setExporting]=useState(false);
  const visible=rows.filter(r=>`${r.firstName} ${r.lastName} ${r.studentCode}`.toLowerCase().includes(q.trim().toLowerCase()));
  const stats=rosterStats(rows,Object.fromEntries(Object.entries(draft).map(([id,v])=>[id,v.status])));
  const changes=Object.keys(draft).length;
  async function exportCsv(){if(!session.classGroup)return;setExporting(true);setExportError(null);try{await downloadFile(`/attendance/export?classGroupId=${session.classGroup.id}`, 'class-attendance.csv');}catch(e){setExportError(apiErrorMessage(e, 'Could not save. Please try again.'));}finally{setExporting(false);}}
  return <section className="card min-w-0 border border-base-300 bg-base-100"><div className="border-b border-base-300 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs text-muted">{session.classGroup?.name}</p><h2 className="mt-1 text-xl font-semibold">{session.title||'Class attendance'}</h2><p className="mt-2 text-xs text-muted">{new Date(session.startAt).toLocaleDateString('en-GB',{day:'numeric',month:'short'})} · {new Date(session.startAt).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'})}</p></div><button onClick={()=>void exportCsv()} disabled={exporting||!session.classGroup} className="btn btn-sm"><FiDownload aria-hidden/>Class report</button></div><div className="mt-5"><StatsStrip {...stats}/></div>{!editable&&!saving?<p className="mt-4 rounded-xl bg-base-200 p-3 text-xs">{session.status==='CANCELLED'?'This session was cancelled. Attendance cannot be marked.':'Attendance opens when the session begins.'}</p>:null}{exportError?<p role="alert" className="mt-3 text-xs text-error">{exportError}</p>:null}</div>
    <div className="p-5"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><input aria-label="Find a student in attendance" value={q} onChange={e=>setQ(e.target.value)} placeholder="Find a student" className="input input-sm w-full sm:w-64"/></div><fieldset disabled={!editable} className="min-w-0"><BulkBar disabled={!editable||!visible.length} onPick={status=>visible.forEach(r=>change(r.studentId,status))} onClear={discard}/><ul className="mt-4 space-y-3">{visible.map(r=><AttendanceRow key={r.studentId} firstName={r.firstName} lastName={r.lastName} studentCode={r.studentCode} current={draft[r.studentId]?.status??r.status??''} savedStatus={r.status} note={draft[r.studentId]?.note??r.note??''} onNote={note=>change(r.studentId,draft[r.studentId]?.status??r.status??'',note)} onPick={status=>change(r.studentId,status)} />)}</ul></fieldset>{!rows.length?<p className="py-8 text-center text-sm text-muted">No eligible students were enrolled for this session.</p>:!visible.length?<p className="py-8 text-center text-sm text-muted">No students match your search.</p>:null}</div>
    <div className="sticky bottom-0 rounded-b-box border-t border-base-300 bg-base-100 p-4 sm:p-5">{error?<p role="alert" className="mb-3 text-xs text-error">{error}</p>:null}{saved?<p role="status" className="mb-3 text-xs text-success">Attendance saved.</p>:null}<div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-semibold">{changes?`${changes} unsaved changes`:`${stats.marked} of ${stats.total} students marked`}</p></div><div className="flex gap-2"><button onClick={discard} disabled={saving||!changes} className="btn btn-sm btn-ghost">Discard</button><button onClick={()=>void save()} disabled={!editable||!changes||Object.values(draft).some(v=>!v.status)} className="btn btn-sm btn-neutral"><FiSave aria-hidden/>{saving?'Saving…':'Save attendance'}</button></div></div></div>
  </section>;
}
