import { FiBookOpen,FiExternalLink } from 'react-icons/fi';
import { dateLabel,responseLabels } from './format';
import type { Homework } from './types';
export function HomeworkGuide({ assignment: a }: { assignment: Homework }) {
  return <aside className="space-y-4">
    <section className="card border border-base-300/70 bg-base-100 p-5"><h2 className="mb-4 text-sm font-semibold">Before you submit</h2><dl className="space-y-3 text-xs">{[['Response', a.questions?.length ? `${a.questions.length} questions · Untimed` : responseLabels[a.responseType]], ['Deadline', dateLabel(a.dueAt, true)], ['Time to prepare', `About ${a.estimatedMinutes} minutes`], ['Worth', `${a.maxPoints} points`], ['Submissions', `Up to ${a.maxSubmissions}, after teacher review`], ['Late work', a.allowLate ? 'Accepted, marked as late' : 'Not accepted after the deadline']].map(([k, v]) => <div key={k} className="flex justify-between gap-4"><dt className="text-base-content/55">{k}</dt><dd className="max-w-[65%] text-right font-medium">{v}</dd></div>)}</dl></section>
    {a.rubric.length ? <section className="card border border-base-300/70 bg-base-100 p-5"><h2 className="mb-4 text-sm font-semibold">What your teacher looks for</h2><div className="space-y-4">{a.rubric.map(r => <div key={r.title}><p className="flex justify-between gap-3 text-xs font-semibold">{r.title}<span className="shrink-0 text-base-content/50">{r.points} pts</span></p><p className="mt-1 text-xs leading-6 text-base-content/60">{r.description}</p></div>)}</div></section> : null}
    {a.resources.length ? <section className="card border border-base-300/70 bg-base-100 p-5"><h2 className="mb-3 flex items-center gap-2 text-sm font-semibold"><FiBookOpen />Helpful resources</h2>{a.resources.map(r => <a key={r.url} href={r.url} target="_blank" rel="noopener noreferrer" className="flex items-center justify-between gap-3 border-t border-base-300/60 py-3 text-xs font-medium hover:text-primary">{r.title}<FiExternalLink className="shrink-0" /></a>)}</section> : null}
    <div className="rounded-box bg-success/5 p-5 text-xs leading-6 text-base-content/65"><strong className="block text-base-content">Make it your own.</strong>Use what you’ve learned, check your German, and ask your teacher if the instructions are unclear. You can leave homework and come back to your saved draft.</div>
  </aside>;
}
