// Run against the seeded local development database:
// NODE_ENV=test LOG_LEVEL=silent UNPAID_ACCESS=FULL node --import tsx src/modules/assignments/assignment-workflow.integration.ts
import assert from 'node:assert/strict';
import { unlink } from 'node:fs/promises';
import path from 'node:path';
import request from 'supertest';
import { createApp } from '../../app.js';
import { prisma } from '../../lib/prisma.js';
const app = createApp();
const submissionIds: string[] = [];
const ids: string[] = [], attemptIds: string[] = [], assessmentIds: string[] = [];
const files: string[] = [];
let otherTeacherId: string | undefined;
const stamp = `workflow-${Date.now()}`;
const auth = async (email: string, password: string): Promise<string> => {
  const r = await request(app).post('/api/auth/login').send({ email, password });
  assert.equal(r.status, 200, 'Seeded login must be available');
  return String((r.body as { data: { tokens: { accessToken: string } } }).data.tokens.accessToken);
};
type Submission = { id: string; updatedAt: string; text: string; revision: number; status: string };
try {
  const teacher = await auth('clarisse@sparch.rw', 'Teacher123!'), student = await auth('nella@student.sparch.rw', 'Student123!'), finance = await auth('finance@sparch.rw', 'Finance123!');
  const owner = await prisma.user.findUniqueOrThrow({ where: { email: 'clarisse@sparch.rw' } });
  const otherTeacher = await prisma.user.create({ data: { email: `${stamp}@test.local`, firstName: 'Unassigned', lastName: 'Teacher', passwordHash: owner.passwordHash, role: 'TEACHER', status: 'ACTIVE' } }); otherTeacherId = otherTeacher.id;
  const outsider = await auth(otherTeacher.email, 'Teacher123!');
  const learner = await prisma.student.findUniqueOrThrow({ where: { userId: (await prisma.user.findUniqueOrThrow({ where: { email: 'nella@student.sparch.rw' } })).id } });
  const enrollment = await prisma.enrollment.findFirstOrThrow({ where: { studentId: learner.id, status: 'ACTIVE', classGroup: { teacherId: owner.id } } });
  assert.ok(enrollment.classGroupId);
  const input = { classGroupId: enrollment.classGroupId, title: stamp, instructions: 'Write five sentences introducing yourself.', status: 'DRAFT', responseType: 'MIXED', maxPoints: 10, rubric: [{ title: 'German', description: 'Clear sentences', points: 10 }], studentIds: [learner.id] };
  let r = await request(app).post('/api/assignments').set('Authorization', `Bearer ${teacher}`).send(input);
  assert.equal(r.status, 201); const id = String((r.body as { data: { id: string } }).data.id); ids.push(id);
  await request(app).get(`/api/assignments/my/${id}`).set('Authorization', `Bearer ${student}`).expect(404);
  await request(app).get('/api/assignments').set('Authorization', `Bearer ${finance}`).expect(403);
  await request(app).get(`/api/assignments/${id}`).expect(401);
  await request(app).put(`/api/assignments/${id}`).set('Authorization', `Bearer ${teacher}`).send({ ...input, status: 'PUBLISHED' }).expect(200);
  await request(app).get(`/api/assignments/my/${id}`).set('Authorization', `Bearer ${student}`).expect(200);
  await request(app).get(`/api/assignments/${id}`).set('Authorization', `Bearer ${outsider}`).expect(404);
  await request(app).post('/api/assignments').set('Authorization', `Bearer ${outsider}`).send(input).expect(403);
  const outsideList = await request(app).get('/api/assignments').set('Authorization', `Bearer ${outsider}`); assert.equal((outsideList.body as { data: unknown[] }).data.length, 0);
  r = await request(app).put(`/api/assignments/my/${id}/draft`).set('Authorization', `Bearer ${student}`).send({ text: 'Ich heiße Nella.', fileIds: [], version: null });
  assert.equal(r.status, 200); let draft = (r.body as { data: Submission }).data;
  await request(app).put(`/api/assignments/my/${id}/draft`).set('Authorization', `Bearer ${student}`).send({ text: 'stale', fileIds: [], version: null }).expect(409);
  r = await request(app).get(`/api/assignments/${id}`).set('Authorization', `Bearer ${teacher}`);
  assert.equal((r.body as { data: { submissions: Submission[] } }).data.submissions[0].text, '', 'Unsubmitted text stays private');
  r = await request(app).post(`/api/assignments/my/${id}/files`).set('Authorization', `Bearer ${student}`).attach('file', Buffer.from('%PDF-1.4\nTest'), { filename: 'worksheet.pdf', contentType: 'application/pdf' });
  assert.equal(r.status, 201); const fileId = String((r.body as { data: { id: string } }).data.id);
  files.push((await prisma.assignmentFile.findUniqueOrThrow({ where: { id: fileId } })).storageName);
  await request(app).get(`/api/assignments/${id}/files/${fileId}`).set('Authorization', `Bearer ${teacher}`).expect(404);
  await request(app).get(`/api/assignments/${id}/files/${fileId}`).set('Authorization', `Bearer ${student}`).expect(200);
  r = await request(app).post(`/api/assignments/my/${id}/submit`).set('Authorization', `Bearer ${student}`).send({ text: draft.text, fileIds: [fileId], version: draft.updatedAt });
  assert.equal(r.status, 200); draft = (r.body as { data: Submission }).data; assert.equal(draft.revision, 1); submissionIds.push(draft.id);
  await request(app).post(`/api/assignments/my/${id}/submit`).set('Authorization', `Bearer ${student}`).send({ text: 'duplicate', version: draft.updatedAt }).expect(403);
  await request(app).get(`/api/assignments/${id}/files/${fileId}`).set('Authorization', `Bearer ${teacher}`).expect(200);
  await request(app).post(`/api/assignments/${id}/submissions/${draft.id}/review`).set('Authorization', `Bearer ${teacher}`).send({ action: 'RETURN', feedback: 'Add where you live.' }).expect(200);
  r = await request(app).get(`/api/assignments/my/${id}`).set('Authorization', `Bearer ${student}`); draft = (r.body as { data: { submission: Submission } }).data.submission;
  r = await request(app).post(`/api/assignments/my/${id}/submit`).set('Authorization', `Bearer ${student}`).send({ text: 'Ich heiße Nella. Ich wohne in Kigali.', fileIds: [fileId], version: draft.updatedAt });
  assert.equal(r.status, 200); draft = (r.body as { data: Submission }).data; assert.equal(draft.revision, 2);
  await request(app).post(`/api/assignments/${id}/submissions/${draft.id}/review`).set('Authorization', `Bearer ${teacher}`).send({ action: 'GRADE', score: 99, feedback: 'Gut gemacht.', rubricScores: [11] }).expect(400);
  await request(app).post(`/api/assignments/${id}/submissions/${draft.id}/review`).set('Authorization', `Bearer ${teacher}`).send({ action: 'GRADE', feedback: 'Gut gemacht.', rubricScores: [9] }).expect(200);
  const versions = await prisma.assignmentVersion.findMany({ where: { submissionId: draft.id }, orderBy: { revision: 'asc' } });
  assert.equal(versions.length, 2); assert.equal(versions[0].feedback, 'Add where you live.'); assert.equal(Number(versions[1].score), 9);
  await request(app).put(`/api/assignments/${id}`).set('Authorization', `Bearer ${teacher}`).send({ ...input, status: 'PUBLISHED', maxPoints: 20, rubric: [] }).expect(409);
  const closed = await prisma.assignment.create({ data: { classGroupId: enrollment.classGroupId, createdById: owner.id, title: stamp, instructions: 'Closed deadline test', status: 'PUBLISHED', dueAt: new Date(Date.now() - 60000), allowLate: false } }); ids.push(closed.id);
  await request(app).put(`/api/assignments/my/${closed.id}/draft`).set('Authorization', `Bearer ${student}`).send({ text: 'Late', version: null }).expect(403);
  await prisma.assignment.update({ where: { id: closed.id }, data: { allowLate: true } });
  const late = await request(app).post(`/api/assignments/my/${closed.id}/submit`).set('Authorization', `Bearer ${student}`).send({ text: 'Late', version: null }); assert.equal(late.status, 200);
  const lateId = String((late.body as { data: { id: string } }).data.id); submissionIds.push(lateId);
  assert.equal((await prisma.assignmentVersion.findFirstOrThrow({ where: { submissionId: lateId } })).isLate, true);
  // Timed assessments restore the same attempt and saved answers; expiry uses the stored draft.
  const assessment = await prisma.assessment.create({ data: { levelId: enrollment.levelId, title: stamp, type: 'QUIZ', durationMinutes: 1, maxAttempts: 1, isPublished: true } }); assessmentIds.push(assessment.id);
  const q = await prisma.question.findFirstOrThrow({ where: { levelId: enrollment.levelId, type: 'SINGLE_CHOICE' } });
  await prisma.assessmentQuestion.create({ data: { assessmentId: assessment.id, questionId: q.id, order: 0 } });
  r = await request(app).post(`/api/assessments/my/assessments/${assessment.id}/attempts`).set('Authorization', `Bearer ${student}`).send({});
  assert.equal(r.status, 201); const attemptId = String((r.body as { data: { id: string } }).data.id); attemptIds.push(attemptId);
  await request(app).get(`/api/assessments/attempts/${attemptId}`).set('Authorization', `Bearer ${outsider}`).expect(404);
  await request(app).put(`/api/assessments/my/attempts/${attemptId}/draft`).set('Authorization', `Bearer ${student}`).send({ responses: { [q.id]: q.correctAnswer } }).expect(200);
  r = await request(app).post(`/api/assessments/my/assessments/${assessment.id}/attempts`).set('Authorization', `Bearer ${student}`).send({}); assert.equal((r.body as { data: { id: string } }).data.id, attemptId);
  await prisma.attempt.update({ where: { id: attemptId }, data: { startedAt: new Date(Date.now() - 120000) } });
  await request(app).put(`/api/assessments/my/attempts/${attemptId}/draft`).set('Authorization', `Bearer ${student}`).send({ responses: {} }).expect(400);
  await request(app).post(`/api/assessments/my/attempts/${attemptId}/submit`).set('Authorization', `Bearer ${student}`).send({ answers: [] }).expect(200);
  assert.deepEqual((await prisma.answer.findFirstOrThrow({ where: { attemptId } })).response, q.correctAnswer);
  const protectedQuiz = await prisma.assessment.create({ data: { levelId: enrollment.levelId, title: stamp, type: 'FINAL_EXAM', protectedMode: true, maxAttempts: 1, isPublished: true } }); assessmentIds.push(protectedQuiz.id);
  await prisma.assessmentQuestion.create({ data: { assessmentId: protectedQuiz.id, questionId: q.id, order: 0 } });
  const begun = await request(app).post(`/api/assessments/my/assessments/${protectedQuiz.id}/attempts`).set('Authorization', `Bearer ${student}`).send({});
  const protectedId = String((begun.body as { data: { id: string } }).data.id); attemptIds.push(protectedId);
  // Force review must remain safe even when a violation report races with submission.
  const flagged = await request(app).post(`/api/assessments/my/attempts/${protectedId}/submit`).set('Authorization', `Bearer ${student}`).send({ requestReview: true, answers: [{ questionId: q.id, response: q.correctAnswer }] });
  assert.equal(flagged.status, 200); assert.equal((flagged.body as { data: { status: string } }).data.status, 'SUBMITTED');
  assert.equal((await prisma.attempt.findUniqueOrThrow({ where: { id: protectedId } })).cheatFlagged, true);
  process.stdout.write('PASS: draft privacy, concurrency, class ownership, attachments, revision history, rubric grading, deadline enforcement and assessment resume.\n');
} finally {
  await prisma.attempt.deleteMany({ where: { id: { in: attemptIds } } });
  await prisma.assessment.deleteMany({ where: { id: { in: assessmentIds } } });
  await prisma.assignment.deleteMany({ where: { id: { in: ids } } });
  await prisma.notification.deleteMany({ where: { title: { contains: stamp } } });
  await prisma.auditLog.deleteMany({ where: { entityId: { in: [...ids, ...attemptIds, ...submissionIds] } } });
  await prisma.activityEvent.deleteMany({ where: { title: { contains: stamp } } });
  for (const file of files) await unlink(path.resolve('uploads', 'assignments', file)).catch(() => {});
  if (otherTeacherId) await prisma.user.delete({ where: { id: otherTeacherId } });
  await prisma.$disconnect();
}
