// NODE_ENV=test LOG_LEVEL=silent UNPAID_ACCESS=FULL node --import tsx src/modules/assignments/assignment-questions.integration.ts
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import request from 'supertest';
import { createApp } from '../../app.js';
import { prisma } from '../../lib/prisma.js';
const app = createApp(), ids: string[] = [], questionIds: string[] = [], submissionIds: string[] = [];
const stamp = `question-workflow-${Date.now()}`;
const auth = async (email: string, password: string): Promise<string> => {
  const r = await request(app).post('/api/auth/login').send({ email, password }); assert.equal(r.status, 200);
  return `Bearer ${String((r.body as { data: { tokens: { accessToken: string } } }).data.tokens.accessToken)}`;
};
type Task = { id: string; status: string; maxPoints: string; questions: { question: { id: string; correctAnswer?: unknown; prompt: string } }[]; summary?: { assigned: number; toReview: number } };
type Work = { id: string; updatedAt: string; questionScores: (number | null)[]; responses: Record<string, unknown> };
try {
  const teacher = await auth('clarisse@sparch.rw', 'Teacher123!'), student = await auth('nella@student.sparch.rw', 'Student123!'), finance = await auth('finance@sparch.rw', 'Finance123!');
  const owner = await prisma.user.findUniqueOrThrow({ where: { email: 'clarisse@sparch.rw' } });
  const learner = await prisma.student.findUniqueOrThrow({ where: { userId: (await prisma.user.findUniqueOrThrow({ where: { email: 'nella@student.sparch.rw' } })).id } });
  const enrollment = await prisma.enrollment.findFirstOrThrow({ where: { studentId: learner.id, status: 'ACTIVE', classGroup: { teacherId: owner.id } } }); assert.ok(enrollment.classGroupId);
  const choice = { id: randomUUID(), type: 'SINGLE_CHOICE', prompt: stamp, options: ['Hallo', 'Tschüss'], correctAnswer: 'Hallo', points: 2, skill: 'VOCABULARY', difficulty: 'EASY', audioUrl: null, imageUrl: null };
  const essay = { id: randomUUID(), type: 'ESSAY', prompt: `${stamp} introduce yourself`, options: null, correctAnswer: null, points: 4, skill: 'WRITING', difficulty: 'EASY', audioUrl: null, imageUrl: null };
  const foreign = { id: randomUUID() };
  const input = { classGroupId: enrollment.classGroupId, title: stamp, instructions: 'Answer the questions at your own pace.', status: 'DRAFT', questions: [choice, essay], maxPoints: 6, studentIds: [learner.id] };
  await request(app).post('/api/assignments').set('Authorization', teacher).send({ ...input, questions: [{ ...choice, correctAnswer: 'Invalid option' }] }).expect(400);
  await request(app).post('/api/assignments').set('Authorization', teacher).send({ ...input, rubric: [{ title: 'Rubric', points: 6 }] }).expect(400);
  const created = await request(app).post('/api/assignments').set('Authorization', teacher).send({ ...input, maxPoints: 1 }).expect(201);
  const task = (created.body as { data: Task }).data; ids.push(task.id); assert.equal(Number(task.maxPoints), 6);
  await request(app).get(`/api/assignments/my/${task.id}`).set('Authorization', student).expect(404);
  await request(app).patch(`/api/assignments/${task.id}/status`).set('Authorization', finance).send({ status: 'PUBLISHED' }).expect(403);
  await request(app).patch(`/api/assignments/${task.id}/status`).set('Authorization', teacher).send({ status: 'PUBLISHED' }).expect(200);
  const mine = await request(app).get(`/api/assignments/my/${task.id}`).set('Authorization', student).expect(200);
  assert.equal((mine.body as { data: { assignment: Task } }).data.assignment.questions[0].question.correctAnswer, undefined);
  const mineList = await request(app).get('/api/assignments/my').set('Authorization', student).expect(200);
  assert.equal((mineList.body as { data: Task[] }).data.find(t => t.id === task.id)!.questions[0].question.correctAnswer, undefined);
  const responses = { [choice.id]: 'Hallo', [essay.id]: 'Ich heiße Nella.' };
  const draft = await request(app).put(`/api/assignments/my/${task.id}/draft`).set('Authorization', student).send({ responses, version: null }).expect(200);
  const work = (draft.body as { data: Work }).data;
  const staffDraft = await request(app).get(`/api/assignments/${task.id}`).set('Authorization', teacher).expect(200);
  assert.deepEqual((staffDraft.body as { data: { submissions: Work[] } }).data.submissions[0].responses, {});
  await request(app).post(`/api/assignments/my/${task.id}/submit`).set('Authorization', student).send({ responses: { [choice.id]: 'Hallo' }, version: work.updatedAt }).expect(400);
  await request(app).post(`/api/assignments/my/${task.id}/submit`).set('Authorization', student).send({ responses: { ...responses, [foreign.id]: 'Invalid' }, version: work.updatedAt }).expect(400);
  const submitted = await request(app).post(`/api/assignments/my/${task.id}/submit`).set('Authorization', student).send({ responses, version: work.updatedAt }).expect(200);
  const submission = (submitted.body as { data: Work }).data; submissionIds.push(submission.id); assert.deepEqual(submission.questionScores, [2, null]);
  const staffList = await request(app).get('/api/assignments').set('Authorization', teacher).expect(200);
  const summary = (staffList.body as { data: Task[] }).data.find(t => t.id === task.id)!.summary!; assert.equal(summary.assigned, 1); assert.equal(summary.toReview, 1);
  await request(app).put(`/api/assignments/${task.id}`).set('Authorization', teacher).send({ ...input, status: 'PUBLISHED' }).expect(200);
  const staff = await request(app).get(`/api/assignments/${task.id}`).set('Authorization', teacher).expect(200);
  assert.equal((staff.body as { data: { assignment: Task } }).data.assignment.questions[0].question.prompt, stamp);
  await request(app).put(`/api/assignments/${task.id}`).set('Authorization', teacher).send({ ...input, questions: [essay, choice] }).expect(409);
  await request(app).post(`/api/assignments/${task.id}/submissions/${submission.id}/review`).set('Authorization', teacher).send({ action: 'GRADE', feedback: 'Good work', questionScores: [3, 3] }).expect(400);
  await request(app).post(`/api/assignments/${task.id}/submissions/${submission.id}/review`).set('Authorization', teacher).send({ action: 'RETURN', feedback: 'Add where you live.' }).expect(200);
  const returned = await request(app).get(`/api/assignments/my/${task.id}`).set('Authorization', student).expect(200);
  const version = (returned.body as { data: { submission: Work } }).data.submission.updatedAt;
  const resubmitted = await request(app).post(`/api/assignments/my/${task.id}/submit`).set('Authorization', student).send({ responses: { ...responses, [essay.id]: 'Ich heiße Nella. Ich wohne in Kigali.' }, version }).expect(200);
  assert.deepEqual((resubmitted.body as { data: Work }).data.questionScores, [2, null]);
  await request(app).post(`/api/assignments/${task.id}/submissions/${submission.id}/review`).set('Authorization', teacher).send({ action: 'GRADE', feedback: 'Good improvement!', questionScores: [2, 3] }).expect(200);
  const saved = await prisma.assignmentSubmission.findUniqueOrThrow({ where: { id: submission.id }, include: { versions: { orderBy: { revision: 'asc' } } } }); assert.equal(Number(saved.score), 5); assert.equal(saved.versions.length, 2); assert.deepEqual(saved.versions[0].responses, responses);
  const csv = await request(app).get(`/api/assignments/${task.id}/export`).set('Authorization', teacher).expect(200); assert.ok(csv.text.includes('Good improvement!')); assert.ok(String(csv.headers['content-type']).includes('text/csv'));
  await request(app).get(`/api/assignments/${task.id}/export`).set('Authorization', finance).expect(403);
  const copy = await request(app).post(`/api/assignments/${task.id}/duplicate`).set('Authorization', teacher).expect(201);
  const duplicate = (copy.body as { data: Task }).data; ids.push(duplicate.id); assert.equal(duplicate.status, 'DRAFT'); assert.equal(Number(duplicate.maxPoints), 6); assert.deepEqual(duplicate.questions, (staff.body as { data: { assignment: Task } }).data.assignment.questions);
  assert.equal(await prisma.assignmentSubmission.count({ where: { assignmentId: duplicate.id } }), 0);
  await request(app).delete(`/api/assignments/${duplicate.id}`).set('Authorization', teacher).expect(200);
  await request(app).delete(`/api/assignments/${task.id}`).set('Authorization', teacher).expect(409);
  await request(app).patch(`/api/assignments/${task.id}/status`).set('Authorization', teacher).send({ status: 'ARCHIVED' }).expect(200);
  await request(app).get(`/api/assignments/my/${task.id}`).set('Authorization', student).expect(404);
  await request(app).get(`/api/assignments/${task.id}/export`).set('Authorization', teacher).expect(200);
  process.stdout.write('PASS: directly authored questions, private drafts, hidden answer keys, snapshots, revisions, grading, summaries, lifecycle, duplication and CSV export.\n');
} finally {
  await prisma.assignment.deleteMany({ where: { id: { in: ids } } });
  await prisma.question.deleteMany({ where: { id: { in: questionIds } } });
  await prisma.notification.deleteMany({ where: { title: { contains: stamp } } });
  await prisma.auditLog.deleteMany({ where: { entityId: { in: [...ids, ...submissionIds] } } });
  await prisma.$disconnect();
}
