import { Router } from "express";
import { asyncHandler } from "../../lib/async-handler.js";
import { ACADEMIC_ROLES } from "../../lib/roles.js";
import { requireAuth } from "../../middleware/auth.js";
import { requireRole } from "../../middleware/rbac.js";
import { validate } from "../../middleware/validate.js";
import { z } from "zod";
import * as c from "./assignments.controller.js";
import { assignmentBody, assignmentParams, draftBody, reviewBody, submissionParams } from "./assignments.schema.js";
import { downloadAttachment, receiveFile } from "./assignment-files.js";
export const assignmentsRouter = Router();
assignmentsRouter.use(requireAuth);
const student = requireRole("STUDENT"), staff = requireRole(...ACADEMIC_ROLES);
assignmentsRouter.get("/my", student, asyncHandler(c.listMine));
assignmentsRouter.get("/my/:id", student, validate({ params: assignmentParams }), asyncHandler(c.getMine));
assignmentsRouter.put("/my/:id/draft", student, validate({ params: assignmentParams, body: draftBody }), asyncHandler(c.draft));
assignmentsRouter.post("/my/:id/submit", student, validate({ params: assignmentParams, body: draftBody }), asyncHandler(c.submit));
assignmentsRouter.post("/my/:id/files", student, validate({ params: assignmentParams }), receiveFile);
assignmentsRouter.get("/:id/files/:fileId", requireRole("STUDENT", ...ACADEMIC_ROLES), validate({ params: z.object({ id: z.uuid(), fileId: z.uuid() }) }), asyncHandler(downloadAttachment));
assignmentsRouter.get("/classes/:id/students", staff, validate({ params: assignmentParams }), asyncHandler(c.roster));
assignmentsRouter.get("/", staff, asyncHandler(c.list));
assignmentsRouter.post("/", staff, validate({ body: assignmentBody }), asyncHandler(c.create));
assignmentsRouter.get("/:id", staff, validate({ params: assignmentParams }), asyncHandler(c.get));
assignmentsRouter.put("/:id", staff, validate({ params: assignmentParams, body: assignmentBody }), asyncHandler(c.update));
assignmentsRouter.post("/:id/submissions/:submissionId/review", staff, validate({ params: submissionParams, body: reviewBody }), asyncHandler(c.review));
