import { FiArrowDown,FiArrowUp,FiTrash2 } from 'react-icons/fi';
import { QuestionChoices } from './QuestionChoices';
import type { AuthoredQuestion } from './types';
import { newQuestion,questionTypes } from './types';
type Props = { value: AuthoredQuestion; index: number; count: number; locked: boolean; onChange: (q: AuthoredQuestion) => void; onRemove: () => void; onMove: (delta: number) => void };
export function AuthoredQuestionCard({ value: q, index, count, locked, onChange, onRemove, onMove }: Props) {
  return <section className="space-y-4 rounded-box border border-base-300 bg-base-100 p-4 sm:p-5"><div className="flex items-center justify-between gap-3"><h3 className="text-sm font-semibold">Question {index + 1}</h3><div className="flex gap-1"><button type="button" className="btn btn-ghost btn-xs btn-square" aria-label={`Move question ${index + 1} up`} disabled={locked || index === 0} onClick={() => onMove(-1)}><FiArrowUp /></button><button type="button" className="btn btn-ghost btn-xs btn-square" aria-label={`Move question ${index + 1} down`} disabled={locked || index === count - 1} onClick={() => onMove(1)}><FiArrowDown /></button><button type="button" className="btn btn-ghost btn-xs btn-square text-error" aria-label={`Delete question ${index + 1}`} disabled={locked} onClick={onRemove}><FiTrash2 /></button></div></div>
    <div className="grid gap-3 sm:grid-cols-[minmax(0,1fr)_100px]"><label><span className="mb-2 block text-xs font-medium">Question type</span><select className="select select-sm w-full" value={q.type} disabled={locked} onChange={e => onChange({ ...q, type: e.target.value, skill: ['SHORT_TEXT', 'ESSAY'].includes(e.target.value) ? 'WRITING' : q.skill, options: newQuestion(e.target.value).options, correctAnswer: null })}>{!questionTypes.some(([type]) => type === q.type) ? <option value={q.type}>{q.type.toLowerCase()} · existing question</option> : null}{questionTypes.map(([type, label]) => <option key={type} value={type}>{label}</option>)}</select></label><label><span className="mb-2 block text-xs font-medium">Points</span><input required type="number" min="0.01" max={1000} step="0.01" className="input input-sm w-full" aria-label={`Question ${index + 1} points`} value={q.points} disabled={locked} onChange={e => onChange({ ...q, points: Number(e.target.value) })} /></label></div>
    <label className="block"><span className="mb-2 block text-xs font-medium">Question *</span><textarea required maxLength={2000} rows={3} className="textarea w-full" aria-label={`Question ${index + 1} text`} placeholder="Write what students should answer…" value={q.prompt} disabled={locked} onChange={e => onChange({ ...q, prompt: e.target.value })} /></label>
    {q.type === 'SINGLE_CHOICE' || q.type === 'MULTIPLE_CHOICE' ? <QuestionChoices value={q} onChange={onChange} locked={locked} /> : q.type === 'TRUE_FALSE' ? <label className="block"><span className="mb-2 block text-xs font-medium">Correct answer</span><select required className="select select-sm w-full" aria-label={`Question ${index + 1} correct answer`} value={q.correctAnswer == null ? '' : typeof q.correctAnswer === 'boolean' ? q.correctAnswer ? 'True' : 'False' : String(q.correctAnswer)} disabled={locked} onChange={e => onChange({ ...q, correctAnswer: e.target.value })}><option value="">Choose the correct answer</option><option>True</option><option>False</option></select></label> : q.type === 'FILL_BLANK' ? <label className="block"><span className="mb-2 block text-xs font-medium">Expected answer *</span><input required className="input input-sm w-full" aria-label={`Question ${index + 1} correct answer`} value={typeof q.correctAnswer === 'string' ? q.correctAnswer : ''} disabled={locked} onChange={e => onChange({ ...q, correctAnswer: e.target.value })} /></label> : <p className="text-xs leading-6 text-base-content/60">{q.type === 'ESSAY' || q.type === 'SHORT_TEXT' ? 'You’ll review and score this written answer after submission.' : 'This existing question and its answer key are preserved. Change the type to write a new format.'}</p>}
    <details className="text-xs"><summary className="cursor-pointer text-base-content/65">Optional audio or image</summary><div className="mt-3 space-y-3">{(['audioUrl', 'imageUrl'] as const).map(key => <label key={key} className="block"><span className="mb-2 block">{key === 'audioUrl' ? 'Audio' : 'Image'} URL</span><input type="text" className="input input-sm w-full" value={q[key] ?? ''} disabled={locked} onChange={e => onChange({ ...q, [key]: e.target.value || null })} /></label>)}</div></details>
  </section>;
}
