import { FiPlus,FiX } from 'react-icons/fi';
import type { AuthoredQuestion } from './types';
export function QuestionChoices({ value: q, onChange, locked }: { value: AuthoredQuestion; onChange: (q: AuthoredQuestion) => void; locked: boolean }) {
  const options = Array.isArray(q.options) ? q.options.map(String) : [];
  const correct = Array.isArray(q.correctAnswer) ? q.correctAnswer as string[] : typeof q.correctAnswer === 'string' ? [q.correctAnswer] : [];
  function update(index: number, text: string) {
    const old = options[index];
    onChange({ ...q, options: options.map((v, i) => i === index ? text : v), correctAnswer: q.type === 'MULTIPLE_CHOICE' ? correct.map(v => v === old ? text : v) : q.correctAnswer === old ? text : q.correctAnswer });
  }
  return <div className="space-y-3"><p className="text-xs text-muted">Write the choices, then mark {q.type === 'MULTIPLE_CHOICE' ? 'all correct answers' : 'the correct answer'}.</p>{options.map((option, index) => <div key={index} className="flex items-center gap-3"><input type={q.type === 'MULTIPLE_CHOICE' ? 'checkbox' : 'radio'} name={`correct-${q.id}`} aria-label={`Choice ${index + 1} is correct`} className={q.type === 'MULTIPLE_CHOICE' ? 'checkbox checkbox-primary checkbox-sm' : 'radio radio-primary radio-sm'} checked={!!option && correct.includes(option)} disabled={locked || !option.trim()} onChange={e => onChange({ ...q, correctAnswer: q.type === 'MULTIPLE_CHOICE' ? e.target.checked ? [...correct, option] : correct.filter(v => v !== option) : option })} /><input required maxLength={500} className="input input-sm min-w-0 flex-1" aria-label={`Choice ${index + 1}`} placeholder={`Choice ${index + 1}`} value={option} disabled={locked} onChange={e => update(index, e.target.value)} /><button type="button" className="btn btn-ghost btn-sm btn-square" aria-label={`Remove choice ${index + 1}`} disabled={locked || options.length <= 2} onClick={() => onChange({ ...q, options: options.filter((_, i) => i !== index), correctAnswer: q.type === 'MULTIPLE_CHOICE' ? correct.filter(v => v !== option) : q.correctAnswer === option ? null : q.correctAnswer })}><FiX aria-hidden /></button></div>)}<button type="button" className="btn btn-ghost btn-sm" disabled={locked || options.length >= 8} onClick={() => onChange({ ...q, options: [...options, ''] })}><FiPlus aria-hidden />Add choice</button></div>;
}
